import {npcSignature,automaticEffects} from './npc-signatures.mjs';
import {displayName} from './display-names.mjs';
import {digiviceOptions} from './digivice.mjs';
import {NPC_ATTRIBUTE_RULES,validateNpcAttributes} from './npc-rules.mjs';
import {effects as effectOptions,qualities as qualityOptions} from '/creator/catalog.js';
import {applyBackdrop} from './scene-presentation.mjs';
import {apiFetch} from './api-client.mjs';
const sceneId=new URLSearchParams(location.search).get('scene');
const sceneEndpoint='/api/scene'+(sceneId?'?id='+encodeURIComponent(sceneId):'');
import {battleLogEntries} from './battle-log.mjs';
import {initCommandWheel,commandIcon} from './command-wheel.mjs';
import {initCommandOverlay,openCommands,closeCommands} from './command-overlay.mjs';
import {draftNpc} from './npc.mjs';
import {sceneSprite,sheetArt} from './sheet-art.mjs';
import {parsePublicSheet} from './forum-import.mjs';
import {renderInterface,combatantHUD} from './battle-interface.mjs';
import {canChoose,canOperate} from './interface-policy.mjs';
import * as engine from './scene-engine.mjs';
import {ELEMENTS} from './rules.mjs';
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
initCommandWheel();initCommandOverlay();
const modes={normal:'Normal · 4+',advantage:'Vantagem · 3+',disadvantage:'Desvantagem · 5+'};
let restored;try{const response=await apiFetch(sceneEndpoint);if(!response.ok)throw Error();restored=await response.json();}catch{document.querySelectorAll('button').forEach(b=>b.disabled=true);$('#feedback').textContent='Não foi possível carregar a cena salva. Reconecte ao servidor; nenhuma ação foi liberada.';throw Error('Servidor da cena indisponível.');}
const serverDigivice=restored.capabilities?.digivice===true;
let state=restored.state,revision=restored.revision,busy=false,formContext=null;
const cmd=(command,...args)=>({command,args});
async function commit(command,...args){const response=await apiFetch(sceneEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,args,revision,requestId:crypto.randomUUID(),resolutionId:state.activeResolutionId,mode:viewMode})});const data=await response.json();if(data.state){revision=data.revision;if(data.maintenance){maintenanceChoices.clear();for(const [id,value] of Object.entries(data.maintenance))maintenanceChoices.set(id,value);}if(!response.ok){state=data.state;playerId=data.actorId;rebuildSelectors();applyScenePresentation();render();}}if(!response.ok)throw Error(data.error||'A alteração não foi salva.');return data.state;}
const imageData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});
let npcDraft=null,npcSide='enemy',labFlipped=false,narratorAuthorized=false;
let maintenancePairId=null,viewMode='player',playerId=restored.actorId;
async function choosePlayer(id){if(id&&!canChoose(state,viewMode,playerId,id,busy))return;try{if(id){busy=true;state=await commit('claim',id);}playerId=id;if(id)$('#operator').value=id;}catch(error){report(error);}finally{busy=false;render();}}
function controlsEntity(id){const a=selectedActor();return viewMode==='narrator'?(id===a.id||state.humans.some(h=>h.id===id&&h.pairId===a.pairId)):canControl(id);}
function canControl(id){return canOperate(state,viewMode,playerId,id);}
const maintenanceChoices=new Map(Object.entries(restored.maintenance||{}));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const selectedActor=()=>engine.actorById(state,$('#operator').value);
const selectedAlly=()=>selectedActor()?.pairId?selectedActor():state.actors.find(a=>a.pairId)||selectedActor();
const selectedHuman=()=>state.humans.find(h=>h.pairId===selectedAlly()?.pairId);
const selectedPair=()=>engine.pairOf(state,selectedAlly());
const setText=(id,value)=>$('#'+id).textContent=value;
const option=(value,label)=>`<option value="${escape(value)}">${escape(label)}</option>`;
const select=(id,label,options)=>`<label>${label}<select id="${id}">${options}</select></label>`;
const number=(id,label,value=0,min=0,max=30)=>`<label>${label}<input id="${id}" type="number" min="${min}" max="${max}" value="${value}" required></label>`;
const check=(id,label)=>`<label class="check"><input id="${id}" type="checkbox"> ${label}</label>`;
const fieldValue=id=>$('#'+id)?.value||'',numeric=id=>Number(fieldValue(id)),checked=id=>!!$('#'+id)?.checked;
function report(error){setText('feedback',error.message||String(error));$('#feedback').classList.add('error');}
function message(text){setText('feedback',text);$('#feedback').classList.remove('error');}
function diceHTML(roll){if(!roll)return '<span class="dice-wait">AWAITING SIGNAL</span>';const threshold={normal:4,advantage:3,disadvantage:5}[roll.mode];return `<div class="dice-tray">${roll.dice.map(d=>`<span class="die ${d>=threshold?'success':''}">${d}</span>`).join('')}</div><span class="roll-meta">${roll.pool}D6 · ${modes[roll.mode]}${roll.forced?' · FORCED':''}</span><strong class="success-count">${roll.successes} SUCESSO${roll.successes===1?'':'S'}</strong>`;}
function updateHud(actor){const root=$('#'+actor.id+'Hud'),previous=Number(root.dataset.hp??actor.hp),m=engine.markers(engine.currentForm(actor));root.innerHTML=combatantHUD(state,actor,viewMode,viewMode==='player'?actor.id===playerId:actor.id===fieldValue('operator'));root.classList.toggle('low-hp',actor.hp>0&&actor.hp/m.hp<=.25);root.dataset.hp=actor.hp;if(previous!==actor.hp){const fill=root.querySelector('.hp-fill');fill.style.width=Math.min(100,previous/m.hp*100)+'%';requestAnimationFrame(()=>fill.style.width=Math.max(0,actor.hp/m.hp*100)+'%');if(previous>actor.hp){const loss=document.createElement('span');loss.className='hp-loss';loss.textContent=previous+' → '+actor.hp;root.append(loss);setTimeout(()=>loss.remove(),1000);}}}
function renderTeams(){
 for(const side of ['ally','enemy']){const actors=state.actors.filter(a=>a.side===side),team=$('#'+side+'Team');team.classList.toggle('multiple',actors.length>1);const ids=actors.map(a=>a.id).join(',');if(team.dataset.roster!==ids){team.dataset.roster=ids;team.innerHTML=actors.map(a=>`<div class="combatant ${side}" id="${a.id}Combatant"><div class="combatant-dock"><div class="combatant-label" id="${a.id}Hud"></div><button class="unit-select" data-unit="${a.id}">CONTROLAR</button></div><div class="sprite-anchor" id="${a.id}"><div class="sprite-position"><img class="sprite" alt="" draggable="false"></div></div><div class="ground-ring" aria-hidden="true"></div></div>`).join('');team.querySelectorAll('.sprite-anchor').forEach(node=>{node.onclick=()=>{const target=engine.actorById(state,node.id);if(target.side!==selectedActor().side&&target.hp&&canControl(selectedActor().id)&&selectedActor().remaining&&!busy)openAction('attack','Atacar',target.id);};});team.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{if(viewMode==='narrator'&&canChoose(state,viewMode,playerId,b.dataset.unit,busy)){$('#operator').value=b.dataset.unit;render();}});}for(const a of actors)$('#'+a.id+'Combatant').classList.toggle('selected',a.id===fieldValue('operator'));}
}
function rebuildSelectors(){for(const id of ['operator','labActor']){const previous=fieldValue(id);$('#'+id).innerHTML=state.actors.map(a=>option(a.id,(a.side==='ally'?'ALIADO':'NPC')+' // '+engine.currentForm(a).name)).join('');$('#'+id).value=state.actors.some(a=>a.id===previous)?previous:state.actors[0]?.id||'';}}
function render(){renderTeams();
 const hasActor=!!selectedActor();
 $('#commandPanel').hidden=!hasActor;$('#openLab').disabled=busy||!hasActor;$('#editResources').disabled=busy||!hasActor;$('#removeActor').disabled=busy||!hasActor;
 if(!hasActor){
  setText('sceneName',state.scene.name);setText('teamCounts','0 × 0');setText('round','ROUND '+pad(state.round));setText('dataOrigin','CENA EM PREPARAÇÃO');setText('sceneStatus','ADICIONE PARTICIPANTES');setText('actorActionStatus','NENHUM PARTICIPANTE');
  $('#pairHud').hidden=true;$('#incomingBanner').hidden=true;$('#operator').disabled=true;
  $('#addAlly').disabled=busy;$('#addEnemy').disabled=busy;$('#reset').disabled=busy;
  renderInterface({state,mode:viewMode,playerId,busy,choose:choosePlayer});$('#roundProgression').hidden=true;$('#roundChecklist').hidden=true;renderLog();return;
 }

 const ally=selectedAlly(),human=selectedHuman()||{id:null,name:'',energy:0,remaining:0,characteristics:{},talents:[]},pair=engine.pairOf(state,ally)||{id:null,level:0,bond:0},actor=selectedActor(),f=engine.currentForm(actor),maxBond=pair.level+5;
 if(maintenancePairId!==pair.id){maintenancePairId=pair.id;const choices=maintenanceChoices.get(pair.id)||{sustain:true,allowZero:false,rescueEnabled:false};$('#sustain').checked=choices.sustain;$('#allowZero').checked=choices.allowZero;}
 setText('dataOrigin',state.actors.some(a=>a.source)?'LOCAL · FICHAS PÚBLICAS + LAB':'LOCAL · FICHAS FICTÍCIAS');setText('teamCounts',state.actors.filter(a=>a.side==='ally').length+' × '+state.actors.filter(a=>a.side==='enemy').length);for(const [id,side] of [['addAlly','ally'],['addEnemy','enemy']])$('#'+id).disabled=busy||state.actors.filter(a=>a.side===side).length>=5;$('#removeActor').disabled=busy;setText('sceneName',state.scene.name);setText('round','ROUND '+pad(state.round));setText('humanName',human.name);setText('energy',`${human.energy} / ${9+pair.level}`);setText('bond',`${pair.bond} / ${maxBond}`);setText('bondLevel',`NÍVEL DE LAÇO ${pair.level}${pair.bond<0?' · LAÇO ENFRAQUECIDO':''}${pair.bond<=-6?' · QUEBRA DE LAÇO':''}`);
 setText('digimonStatus',ally.remaining&&ally.hp?'AVAILABLE':'LOCKED');setText('humanStatus',human.energy===0?'OUT':human.skipped?human.lastAction||'SKIPPED':human.remaining?'AVAILABLE':'USED');setText('turnStatus',busy?'PROCESSING':state.phase==='closed'?'ROUND CLOSED':engine.roundStatus(state).ready?'RODADA PRONTA':engine.partnershipStatus(state,pair.id).label);setText('sceneStatus',busy?'PROCESSING ACTION':engine.pendingResolutions(state).length?engine.pendingResolutions(state).length+' ACTIONS WAITING':state.phase==='closed'?'RODADA ENCERRADA':engine.roundStatus(state).ready?'RODADA CONCLUÍDA':'AGUARDANDO AÇÃO');
 for(const a of state.actors){const af=engine.currentForm(a),m=engine.markers(af),root=$('#'+a.id);updateHud(a);root.querySelector('img').src=sceneSprite(af);root.querySelector('img').classList.toggle('pixel-art',!!galleryArts.find(art=>new URL(art.image,location.href).href===new URL(af.image,location.href).href)?.pixelArt);root.querySelector('img').alt=af.name;root.querySelector('img').style.setProperty('--sprite-flip',a.flipped?-1:1);root.style.setProperty('--idle-duration',(4.2+state.actors.indexOf(a)*.31)+'s');root.style.setProperty('--idle-delay',(-state.actors.indexOf(a)*.63)+'s');root.querySelector('.sprite-position').style.transform=`translate(${a.position.x}px,${a.position.y}px)`;root.style.setProperty('--unit-scale',a.position.scale);root.classList.toggle('defeated',a.hp===0);root.classList.toggle('low-hp',a.hp>0&&a.hp/m.hp<=.25);$('#'+a.id+'Combatant').classList.toggle('shielded',a.defending);}
 setText('actorController',actor.controller==='player'?'PLAYER // ALIADO':'NARRADOR // NPC');setText('actorActionStatus',actor.hp===0?'OUT':actor.remaining?'ACTION AVAILABLE':'ACTION LOCKED');setText('signatureUses',`${actor.uses[actor.formId]??f.attributes.intelligence} / ${f.attributes.intelligence} USOS`);
 const blocked=busy||state.phase!=='open'||(engine.entityPending(state,actor.id)&&!engine.canContinueMulti(state,actor.id))||actor.remaining===0||!actor.hp||actorPairFinalized(actor);document.querySelectorAll('[data-action]').forEach(b=>b.disabled=blocked||engine.canContinueMulti(state,actor.id)&&!['attack','signature'].includes(b.dataset.action)||['attack','signature'].includes(b.dataset.action)&&engine.incomingAttacks(state,actor.id).length>0||b.dataset.action==='defend'&&engine.incomingAttacks(state,actor.id).some(r=>r.pending.dodge)||b.dataset.action==='signature'&&!f.attacks.length);$('#skipNpc').hidden=actor.controller!=='narrator';$('#skipNpc').disabled=blocked;
 if(pair.turnFinalized&&!busy&&state.phase==='open')setText('turnStatus','TURNO CONCLUÍDO');
 const humanBlocked=(selectedActor().controller!=='player'&&viewMode!=='narrator')||busy||state.phase!=='open'||engine.entityPending(state,human.id)||!human.remaining||!human.energy||pair.turnFinalized;const coordinates=human.observedRound===state.round-1;$('#humanObserve').setAttribute('aria-describedby','observeHelp');$('#humanObserve b').textContent=coordinates?'COORDENADAS':'OBSERVAR';$('#humanObserve small').textContent=coordinates?'+1d6 no ataque':'Preparar coordenadas';$('#humanObserve .command-icon').innerHTML=commandIcon(coordinates?'coordinates':'eye');$('#humanObserve').disabled=humanBlocked||human.observedRound===state.round||human.coordinatesUsedRound===state.round||coordinates&&engine.entityPending(state,ally.id);setText('observeHelp',human.coordinatesUsedRound===state.round?(ally.coordinatesRound===state.round?'Coordenadas enviadas: +1d6 preparado para o próximo ataque nesta rodada.':'O bônus de Coordenadas já foi aplicado ao ataque desta rodada.'):coordinates?'Dar Coordenadas usa a ação do Humano e dá +1d6 ao próximo ataque do seu Digimon nesta rodada.':human.observedRound===state.round?'Observação feita. Dar Coordenadas estará disponível na próxima rodada.':'Ao Observar, na próxima rodada você poderá usar Dar Coordenadas e dar +1d6 ao próximo ataque do seu Digimon.');$('#humanDigivice').disabled=humanBlocked||!canControl(human.id);$('#humanDigivice').setAttribute('aria-disabled',String($('#humanDigivice').disabled));$('#humanAttack').disabled=busy||(humanBlocked&&!engine.canContinueMulti(state,human.id))||engine.incomingAttacks(state,human.id).length>0;
 $('#evolve').disabled=(selectedActor().controller!=='player'&&viewMode!=='narrator')||busy||engine.pairPending(state,pair.id)||state.phase!=='open'||!ally.hp||!human.energy||pair.turnFinalized;
 $('#reset').disabled=busy;$('#openLab').disabled=busy;
 $('#actorDetails').innerHTML=`<div class="stats-grid">${Object.entries(engine.ATTRIBUTES).map(([k,label])=>`<span>${label}<b>${f.attributes[k]}</b></span>`).join('')}<span>Dano<b>${engine.markers(f).damage}</b></span><span>Esquiva base<b>${engine.markers(f).dodge}d6</b></span></div><p>Qualidades: ${escape(f.qualities.map(q=>q.name+' · R'+q.rank).join(' / ')||'Nenhuma')}</p>${f.attacks.map(a=>`<div class="technique"><b>${escape(a.name)}</b><span>R${a.rank} · ${escape(a.element)} · ${escape(a.effect||a.sourceEffects?.join(', ')||'Sem efeito')}</span></div>`).join('')}`;
 if(actor.source){$('#actorDetails').insertAdjacentHTML('beforeend','<p class="sheet-source">Ficha pública: <a target="_blank" rel="noopener" href="'+escape(actor.source.url)+'">'+escape(actor.source.title)+'</a></p>'+actor.importWarnings.map(w=>'<p class="import-warning">'+escape(w)+'</p>').join(''));}const upkeep=engine.STAGES[engine.currentForm(ally).stage];setText('maintenanceCost',`Fim da rodada: ${upkeep.energy} Energia / ${upkeep.bond} PL. Evoluir: custo inicial 0.`);setText('humanDetails',Object.entries(engine.CHARACTERISTICS).map(([k,l])=>l+' '+human.characteristics[k]).join(' · ')+' // Talento: '+human.talents.map(t=>t.name+' '+t.rank).join(', '));
 setText('roundHint','Sem ordem fixa por lado. Resolva os ataques recebidos antes de atacar; conclua ou dispense as ações para encerrar a rodada.');
 $('#operator').disabled=busy;renderResolution();renderIncoming();renderCommandDecisions();renderLog();
 renderInterface({state,mode:viewMode,playerId,busy,choose:choosePlayer});

}
function renderResolution(){renderResolutionQueue();if(busy||state.pending)$('#resolutionPanel').classList.remove('folded');$('#toggleResult').hidden=busy||!state.result;const p=state.pending,r=state.result,body=$('#resultBody');$('#resolutionActions').replaceChildren();setText('processingState',busy?'PROCESSING':p?'AWAITING RESOLUTION':r?'RESOLVED':'STANDBY');
 if(busy){body.innerHTML='<p>PROCESSING ACTION // Os resultados serão revelados no palco.</p>';return;}
 if(p?.kind==='attack'||r?.kind==='attack'){const data=p||r,ready=!!data.dodge,calc=ready?(p?engine.attackResult(p):r):null;body.innerHTML=`<div class="opposed-grid"><div><span class="eyebrow">ATTACK // ${escape(data.context.actor.name)}</span>${data.context.guidanceBonus?'<small class="action-help">Coordenadas aplicadas: +1d6 neste ataque.</small>':''}${diceHTML(data.attack)}</div><span class="opposed-vs">VS</span><div><span class="eyebrow">DODGE // ${escape(data.context.target.name)}</span>${diceHTML(data.dodge)}</div></div>${ready?`<div class="damage-equation"><strong class="${calc.hit?'hit':'miss'}">${calc.hit?'HIT CONFIRMED':'MISS // DODGE SUCCESSFUL'}</strong><span>${data.attack.successes} ataque − ${data.dodge.successes} esquiva = ${calc.difference} diferença</span><span>Dano base ${calc.base} + diferença ${Math.max(0,calc.difference)} + Atributo Digital ${calc.digital} + Pesado ${calc.heavy}${calc.weak?' · Fraco: metade':''}</span><b>FINAL DAMAGE // ${calc.damage} ${data.context.targetType==='human'?'Energia':'PV'}${p?' · AGUARDA ACEITE':''}</b>${!p?`<span>${data.context.targetType==='human'?'Energia':'PV'} ${r.hpBefore} → ${r.hpAfter}${r.effectApplied?' · '+engine.CONDITIONS[r.effectApplied]:''}</span>`:''}</div>`:'<p>'+ (data.attackConfirmed===false?'O atacante pode aceitar ou forçar esta rolagem antes da defesa.':'Ataque confirmado. Aguardando a reação do alvo.')+'</p>'}`;
 if(p){const attacker=engine.entityById(state,p.context.actorId),defender=engine.entityById(state,p.context.targetId);
 if(p.attackConfirmed===false){if(controlsEntity(attacker.id)){if(!p.attackForced&&engine.pairOf(state,attacker))resolutionButton('FORÇAR ATAQUE · −2 PL',()=>confirmForce('attack'));resolutionButton('ACEITAR ROLAGEM DE ATAQUE',()=>run(cmd('confirmAttack'),'ATAQUE CONFIRMADO'),true);if(engine.canAcceptAttackMulti(state))resolutionButton('ACEITAR RESULTADO E REALIZAR MULTI-ATTACK · 2 PL',()=>run(cmd('confirmAttackMulti'),'MULTI-ATTACK RESERVADO'));}else resolutionNotice('Aguardando o atacante aceitar ou forçar sua rolagem.');}
 else if(engine.awaitingMultiAttacks(state,p)){if(controlsEntity(attacker.id)&&engine.canContinueMulti(state,attacker.id))resolutionButton('ROLAR SEGUNDO ATAQUE DO MULTI-ATTACK',()=>openAction(p.context.entityType==='human'?'human-attack':'attack','Segundo ataque',p.context.targetId),true);else resolutionNotice('Aguardando a confirmação dos dois ataques do Multi-Attack.');}
 else if(!p.dodge){if(controlsEntity(defender.id))resolutionButton('⚡ ROLAR ESQUIVA // '+engine.entityName(defender),()=>openAction('dodge'),true);else resolutionNotice('Aguardando o controlador de '+engine.entityName(defender)+' rolar a esquiva.');}
 else if(p.reviewFlow&&!p.defenseConfirmed){if(controlsEntity(defender.id)){if(engine.attackResult(p).hit&&!p.dodgeForced&&engine.pairOf(state,defender))resolutionButton('FORÇAR ESQUIVA · −2 PL',()=>confirmForce('dodge'));resolutionButton('ACEITAR RESULTADO / APLICAR',async()=>{try{state=await commit('confirmDodge');if(engine.survivalOffer(state)){render();return;}await accept();}catch(e){report(e);}},true);}else resolutionNotice('Aguardando o defensor aceitar ou forçar a esquiva.');}
 else{const offer=engine.survivalOffer(state);if(offer){body.insertAdjacentHTML('beforeend','<div class="survival-offer"><strong>FORÇA PARA LUTAR // '+escape(offer.name)+'</strong><p>Este golpe levará '+offer.resource+' a 0. Gastar 3 PL para permanecer com 1?</p></div>');if(controlsEntity(offer.id)){resolutionButton('USAR 3 PL · PERMANECER COM 1',async()=>{state=await commit('decideSurvival',true);await accept();},true);resolutionButton('ACEITAR 0 '+offer.resource.toUpperCase(),async()=>{state=await commit('decideSurvival',false);await accept();});}else resolutionNotice('Aguardando a decisão de sobrevivência do defensor.');}else if(controlsEntity(attacker.id)||controlsEntity(defender.id))resolutionButton('ACEITAR RESULTADO / APLICAR',accept,true);else resolutionNotice('O controlador do combate deve aplicar o resultado.');}}
 }else if(p?.kind==='test'||r?.kind==='test'){const t=p||r;body.innerHTML=`<div class="generic-result"><span class="eyebrow">${escape(t.name)} // ${escape(t.action)}</span>${diceHTML(t.roll)}<strong>${t.roll.successes>=t.difficulty?'SUCCESS':'FAIL'} · ${t.roll.successes} / ${t.difficulty} SUCESSOS</strong><p>${escape(t.description)}</p></div>`;if(p&&canControl(p.entityId)){const entity=p.entityType==='human'?engine.humanById(state,p.entityId):engine.actorById(state,p.entityId);if(p.roll.successes<p.difficulty&&!p.forced&&engine.pairOf(state,entity))resolutionButton('FORÇAR TESTE · −2 PL',()=>confirmForce('test'));resolutionButton('ACEITAR RESULTADO',accept,true);}}
 else body.innerHTML=`<p>${escape(r?.summary||'A mecânica registra o que acontece. Configure o ataque; a Esquiva é uma reação, não uma ação normal do turno.')}</p>`;
 if(r?.kind==='canceled')body.innerHTML='<p>'+escape(r.summary)+'</p>';
 if(r?.summary)setText('resultAnnouncement',r.summary);
}
// Reuse the real resolution controls, retaining their handlers and permissions.
function renderCommandDecisions(){
 const p=state.pending,card=$('#commandRoll'),decision=$('#commandDecision'),actions=$('#resolutionActions'),incoming=$('#incomingBanner');
 $('#commandDecisionActions').append(actions,incoming);
 const rescue=state.resourceSurvival;
 if(rescue&&!busy){card.hidden=decision.hidden=false;$('#commandStage').classList.add('has-decision');setText('decisionHeading','FORÇA PARA LUTAR');setText('decisionHint',`Gastar 3 PL para permanecer com 1 ${rescue.resource}?`);card.innerHTML='<h3>RECURSO ESGOTADO</h3><b>'+escape(rescue.name)+'</b>';actions.replaceChildren();incoming.hidden=true;if(controlsEntity(rescue.id)){resolutionButton('USAR 3 PL · PERMANECER COM 1',()=>run(cmd('resourceSurvival',true),'FORÇA PARA LUTAR'),true);resolutionButton('ACEITAR 0 '+rescue.resource.toUpperCase(),()=>run(cmd('resourceSurvival',false),'FORA DE BATALHA'));}else resolutionNotice('Aguardando a decisão do controlador.');return;}
 const visible=!busy&&(!!p||!incoming.hidden);
 card.hidden=decision.hidden=!visible;$('#commandStage').classList.toggle('has-decision',visible);
 if(!visible)return;
 const attack=p?.kind==='attack',offer=attack&&engine.survivalOffer(state);
 setText('decisionHeading',offer?'FORÇA PARA LUTAR':attack?(p.attackConfirmed===false?'REVISE SEU ATAQUE':engine.awaitingMultiAttacks(state,p)?'MULTI-ATTACK // SEGUNDO ATAQUE':!p.dodge?'REAÇÃO DO ALVO':'REVISE O RESULTADO'):'REVISE SUA ROLAGEM');
 setText('decisionHint',offer?`O golpe leva ${offer.resource} a 0. Você pode usar 3 PL para permanecer com 1.`:attack?(p.attackConfirmed===false?(p.attackForced?'Rolagem forçada concluída. Aceite para liberar a esquiva.':'Aceite a rolagem ou force uma nova tentativa por 2 PL.'):engine.awaitingMultiAttacks(state,p)?'Role e confirme o segundo ataque. Depois o alvo resolve uma esquiva para cada golpe.':!p.dodge?'O alvo deve resolver sua esquiva antes de atacar.':'Confira a esquiva e aplique o resultado para concluir a ação.'):'Aceite o resultado ou force o teste, quando disponível.');
 card.innerHTML=p?`<h3>${attack?'ATAQUE EM RESOLUÇÃO':'TESTE EM RESOLUÇÃO'}</h3><b>${escape(attack?p.context.actor.name:p.name)}</b>${attack?`<span class="decision-target">→ ${escape(p.context.target.name)}</span>`:''}${diceHTML(attack?p.attack:p.roll)}${attack&&p.dodge?`<h3>ESQUIVA DO ALVO</h3>${diceHTML(p.dodge)}`:''}`:'<h3>ATAQUES RECEBIDOS</h3><p>Escolha a reação pendente ao lado.</p>';
 // Other incoming attacks remain selectable without duplicating the active reaction.
 if(attack&&actions.querySelector('button')){
  const buttons=[...incoming.querySelectorAll('button')];
  const a=selectedActor(),h=state.humans.find(h=>h.pairId===a.pairId),entries=[...engine.incomingAttacks(state,a.id),...(h?engine.incomingAttacks(state,h.id):[])];
  buttons.forEach((b,i)=>{if(entries[i]?.id===state.activeResolutionId)b.hidden=true;});
  incoming.hidden=!buttons.some(b=>!b.hidden);
 }
}
function resolutionNotice(text){const p=document.createElement('p');p.className='waiting-note';p.textContent=text;$('#resolutionActions').append(p);}
function resolutionButton(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;if(primary)b.className='primary';b.addEventListener('click',fn);$('#resolutionActions').append(b);}
function renderLog(){const entries=battleLogEntries(state);setText('logCount',pad(entries.length)+' EVENTOS');$('#battleLog').replaceChildren(...entries.slice().reverse().map(e=>{const li=document.createElement('li');li.dataset.kind=e.kind;li.innerHTML='<b>R'+pad(e.round)+'</b><span>'+escape(e.summary)+'</span>';return li;}));if(!entries.length)$('#battleLog').innerHTML='<li class="empty-log">Nenhuma ação concluída ainda.</li>';}
async function confirmation(text,labels={}){$('#confirmDialog [value=confirm]').textContent=labels.confirm||'CONFIRMAR';$('#confirmDialog [value=cancel]').textContent=labels.cancel||'CANCELAR';setText('confirmDescription',text);const dialog=$('#confirmDialog');dialog.returnValue='';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true}));}
async function animateRoll(roll,caption){const overlay=$('#diceOverlay'),tray=$('#overlayDice');overlay.hidden=false;overlay.classList.add('processing');setText('overlayCaption',caption+' // '+roll.pool+'D6');setText('overlayResult','PROCESSING ACTION…');$('#arena').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});const spans=Array.from({length:roll.pool},()=>{const d=document.createElement('span');d.className='die';tray.append(d);return d;});tray.replaceChildren(...spans);
 const ticker=setInterval(()=>spans.forEach(d=>d.textContent=1+Math.floor(Math.random()*6)),70);try{await delay(matchMedia('(prefers-reduced-motion: reduce)').matches?60:220);}finally{clearInterval(ticker);overlay.classList.remove('processing');}const threshold={normal:4,advantage:3,disadvantage:5}[roll.mode];for(let i=0;i<spans.length;i++){spans[i].textContent=roll.dice[i];spans[i].classList.toggle('success',roll.dice[i]>=threshold);}setText('overlayResult',`${roll.successes} SUCESSOS // ${modes[roll.mode]}`);await delay(180);overlay.hidden=true;
}
async function run(operation,caption,rollSelector){if(busy)return false;closeCommands();busy=true;render();try{state=await commit(operation.command,...operation.args);maintenancePairId=null;render();if(rollSelector){const roll=rollSelector(state);if(roll)await animateRoll(roll,caption);}message(caption==='RESULT RESOLVED'?state.result?.summary||caption:state.log.at(-1)?.summary||caption);return true;}catch(error){report(error);return false;}finally{busy=false;$('#diceOverlay').hidden=true;render();if(rollSelector&&state.pending)openCommands();}}

function sceneNode(id){const h=engine.humanById(state,id);return h?$('#'+state.actors.find(a=>a.pairId===h.pairId).id+'Hud .hud-human'):$('#'+id);}
async function accept(){if(busy)return;const pending=state.pending,resolved=await run(cmd('acceptResult'),'RESULT RESOLVED');if(resolved&&pending?.kind==='attack'&&!state.pending&&state.result?.kind==='attack'){busy=true;render();const r=state.result,attacker=$('#'+(pending.context.entityType==='human'?state.actors.find(a=>a.pairId===engine.humanById(state,pending.context.actorId).pairId).id:pending.context.actorId)),target=sceneNode(pending.context.targetId);attacker.classList.add('attacking');target.classList.add(r.hit?'damaged':'dodging');if(r.hit){setText('impact','−'+r.damage+(pending.context.targetType==='human'?' ENERGIA':' PV'));const bounds=target.getBoundingClientRect(),arenaBounds=$('#arena').getBoundingClientRect();$('#impact').style.right='auto';$('#impact').style.left=(bounds.left-arenaBounds.left+$('#arena').scrollLeft+bounds.width/2)+'px';$('#impact').classList.add('show');}await delay(250);attacker.classList.remove('attacking');target.classList.remove('damaged','dodging');$('#impact').classList.remove('show');busy=false;const next=engine.pendingResolutions(state).find(entry=>controlsEntity(entry.pending.context?.targetId)&&entry.pending.attackConfirmed&&!engine.awaitingMultiAttacks(state,entry.pending));if(next)state=engine.selectResolution(state,next.id);render();}}
async function confirmForce(side){if(await confirmation('Forçar repete somente este teste com o mesmo grupo de dados. A parceria perde 2 PL, mesmo se ficar negativo. Só uma tentativa extra.'))await run(cmd('forceTest',side),'FORCE TEST',s=>s.pending.kind==='attack'?s.pending[side==='attack'?'attack':'dodge']:s.pending.roll);}
function actionConfig(){const context=formContext;return {actorId:context.actorId,targetId:fieldValue('cfgTarget')||context.targetId,attribute:fieldValue('cfgAttribute'),qualityId:fieldValue('cfgQuality'),signatureId:context.kind==='signature'?fieldValue('cfgSignature'):null,bond:numeric('cfgBond'),mode:fieldValue('cfgMode')||'normal',staged:true,description:'',extraUse:checked('cfgExtra'),useEffect:checked('cfgEffect'),rescueEnabled:false,entityType:context.entityType,entityId:context.entityId,action:context.action,difficulty:numeric('cfgDifficulty'),effort:checked('cfgEffort')};}
function openAction(kind,action='Interagir',targetId=null){
 if(!canControl(kind==='dodge'?state.pending?.context.targetId:selectedActor().id))return;
 document.querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('chosen',b.dataset.action===kind));
 const actor=selectedActor(),human=selectedHuman(),target=kind==='dodge'?engine.entityById(state,state.pending.context.targetId):engine.entityById(state,targetId)||state.actors.find(a=>a.side!==actor.side&&a.hp),entity=kind==='dodge'?target:['human','human-attack'].includes(kind)?human:actor,isHuman=!!entity.characteristics,f=isHuman?null:engine.currentForm(entity),pair=engine.pairOf(state,entity),canSpend=Math.max(0,pair?.bond||0),isTest=['human','interact'].includes(kind);
 formContext={kind,actorId:kind==='human-attack'?human.id:actor.id,targetId:target?.id,entityType:isHuman?'human':'digimon',entityId:entity.id,action};let fields='';setText('actionTitle',kind==='dodge'?`ESQUIVA // ${engine.entityName(target)}`:['human','human-attack'].includes(kind)?`HUMANO // ${action}`:kind==='signature'?'ATAQUE DE ASSINATURA':kind==='interact'?action:'COMO VOCÊ ESTÁ ATACANDO?');
 if(['attack','signature','human-attack'].includes(kind))fields+=select('cfgTarget','ALVO',[...state.actors,...state.humans].filter(a=>engine.entitySide(state,a)!==actor.side&&engine.entityLife(a)>0).map(a=>option(a.id,(a.characteristics?'HUMANO // ':'DIGIMON // ')+engine.entityName(a))).join(''));
 if(kind==='dodge')fields='<p>A esquiva é uma reação e não gasta a ação normal. '+(isHuman?'Humano: Corpo + Talento pertinente.':'Digimon: Agilidade + bônus de estágio + Qualidade pertinente.')+'</p>';
 else fields+=select('cfgAttribute',isHuman?'CARACTERÍSTICA':'ATRIBUTO',Object.entries(kind==='human-attack'?{body:'Corpo'}:isHuman?engine.CHARACTERISTICS:engine.ATTRIBUTES).map(([id,label])=>option(id,`${label} ${isHuman?human.characteristics[id]:f.attributes[id]}`)).join(''));
 fields+=select('cfgQuality',isHuman?'TALENTO RELEVANTE':'QUALIDADE APLICÁVEL',option('','Nenhuma')+(isHuman?entity.talents:f.qualities).map(q=>option(q.id,`${q.name} · Rank ${q.rank}`)).join(''));
 if(kind==='signature')fields+=select('cfgSignature','ATAQUE / RANK / ELEMENTO',f.attacks.map(a=>option(a.id,`${a.name} · R${a.rank} · ${a.element}`)).join(''))+check('cfgExtra','Segura Essa! · 1 PL quando os usos acabarem')+check('cfgEffect','Aplicar efeito opcional em vez de dano integral');
 fields+=`<div class="lab-grid">${number('cfgBond','CHANCES MELHORES · PL',0,0,canSpend)}${select('cfgMode','CIRCUNSTÂNCIA DO NARRADOR',Object.entries(modes).map(([id,label])=>option(id,label)).join(''))}</div>`;
 if(kind==='human-attack')fields+=check('cfgEffort','Esforço · −1 Energia / +1 dado')+'<p>Corpo + Talento relevante. Dano base humano: 1. O alvo rola Esquiva; não consome a ação do seu Digimon.</p>';
 if(isTest)fields+=number('cfgDifficulty','DIFICULDADE DO NARRADOR',2,1,12)+(isHuman?check('cfgEffort','Esforço · −1 Energia / +1 dado'): '')+'<p>Ajudar/interagir registra o teste. O narrador decide a consequência apropriada; não há bônus automático inventado.</p>';

 $('#actionFields').innerHTML=fields;if(targetId&&$('#cfgTarget'))$('#cfgTarget').value=targetId;mountTargetCards();if(viewMode==='player'){if($('#cfgDifficulty'))$('#cfgDifficulty').readOnly=true;if($('#cfgMode'))$('#cfgMode').disabled=true;}$('#confirmAction').disabled=false;$('#confirmAction').textContent=kind==='dodge'?'CONFIRMAR ESQUIVA':'CONFIRMAR E ROLAR';$('#actionDialog').showModal();updatePreview();
}
function updatePreview(){if(!formContext)return;try{const c=actionConfig(),k=formContext.kind;let text;if(k==='digivice'){updateDigivicePreview();return;}if(k==='evolution'){const a=selectedAlly(),f=a.forms[fieldValue('cfgForm')],rule=engine.STAGES[f.stage];text=`DATA RECONSTRUCTION // ${f.name}\nCusto inicial 0. Manutenção: ${rule.energy} Energia / ${rule.bond} PL por rodada.\nDano sofrido preservado; usos compartilhados desta forma não são recarregados.`;setText('configPreview',text);return;}if(['attack','signature','human-attack'].includes(k)){const p=engine.attackPreview(state,c),actor=k==='human-attack'?engine.humanById(state,c.actorId):engine.actorById(state,c.actorId),f=k==='human-attack'?{attributes:{body:actor.characteristics.body}}:engine.currentForm(actor);text=`TOTAL POOL // ${p.pool}D6 · ${modes[p.mode]}\n${engine.ATTRIBUTES[p.attribute]||engine.CHARACTERISTICS[p.attribute]} ${f.attributes[p.attribute]} + Qualidade ${p.quality?.rank||0} + Rank ${p.signature?.rank||0} + Laço ${p.bond} + Coordenadas ${p.guidanceBonus||0}\nElemento ${p.element} · Vantagens: ${p.reasons.advantages.join(', ')||'—'} · Desvantagens: ${p.reasons.disadvantages.join(', ')||'—'}\nDano base ${p.baseDamage} · Bônus Digital ${p.digitalBonus}${p.signature?'\nEfeito: '+(p.signature.effect||p.signature.sourceEffects?.join(', ')||'Sem efeito')+' · Usos da forma '+(actor.uses[actor.formId]??f.attributes.intelligence)+' / '+f.attributes.intelligence+(p.effectAlreadyUsed?' · Efeito já aplicado neste alvo; repetição não disponível':''):''}`;}
 else if(k==='dodge'){const p=engine.dodgePreview(state,c);text=`DODGE POOL // ${p.pool}D6 · ${modes[p.mode]}\nVantagens: ${p.reasons.advantages.join(', ')||'—'} · Desvantagens: ${p.reasons.disadvantages.join(', ')||'—'}`;}
 else{const entity=k==='human'?selectedHuman():selectedActor(),stats=k==='human'?entity.characteristics:engine.currentForm(entity).attributes,q=(k==='human'?entity.talents:engine.currentForm(entity).qualities).find(q=>q.id===c.qualityId);text=`TEST POOL // ${stats[c.attribute]+(q?.rank||0)+c.bond+(c.effort?1:0)}D6 · ${modes[c.mode]}\nDificuldade ${c.difficulty} · Energia ${c.effort?1:0} · PL ${c.bond}`;}setText('configPreview',text);}catch(e){setText('configPreview',e.message);}}
$('#actionForm').addEventListener('input',updatePreview);$('#cancelAction').addEventListener('click',()=>$('#actionDialog').close());$('#actionForm').addEventListener('submit',async e=>{e.preventDefault();const c=actionConfig(),kind=formContext.kind,formId=fieldValue('cfgForm');$('#actionDialog').close();if(kind==='digivice'){await run(cmd('useDigivice',selectedHuman().id,{function:fieldValue('cfgFunction'),kind:fieldValue('cfgBoosterKind'),id:fieldValue('cfgProtocol')}),'DIGIVICE ATIVADO');return;}if(kind==='evolution'){const evolved=await run(cmd('evolveAction',selectedAlly().id,formId),'EVOLUTION ACCESS GRANTED');if(evolved){busy=true;render();const node=$('#'+selectedAlly().id);node.classList.add('evolving');$('#overlayDice').replaceChildren();setText('overlayCaption','DATA RECONSTRUCTION');setText('overlayResult','EVOLUTION ACCESS GRANTED');$('#diceOverlay').hidden=false;$('#arena').scrollIntoView({behavior:'smooth',block:'center'});await delay(700);node.classList.remove('evolving');$('#diceOverlay').hidden=true;busy=false;render();}return;}if(['attack','signature','human-attack'].includes(kind))await run(cmd('beginAttack',c),'ATTACK POOL',s=>s.pending?.attack);else if(kind==='dodge')await run(cmd('rollDodge',c),'DODGE POOL',s=>s.pending?.dodge);else await run(cmd('genericTest',c),'TEST POOL',s=>s.pending?.roll);});
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',async()=>{if(b.dataset.action==='defend'){if(await confirmation('Defender usa a ação deste Digimon e concede Vantagem em Esquivas até sua próxima oportunidade de agir.'))await run(cmd('defend',selectedActor().id,{rescueEnabled:false}),'DEFENDING');}else openAction(b.dataset.action);}));
$('#operator').addEventListener('change',render);$('#humanAttack').addEventListener('click',()=>openAction('human-attack','Ataque Humano'));
$('#skipNpc').addEventListener('click',async()=>{if(await confirmation('Dispensar a ação deste NPC nesta rodada?'))await run(cmd('skipAction','digimon',selectedActor().id),'NPC SKIPPED');});
for(const id of ['sustain','allowZero'])$('#'+id).addEventListener('change',()=>run(cmd('maintenance',{actorId:selectedAlly().id,sustain:checked('sustain'),allowZero:checked('allowZero')}),'MANUTENÇÃO SALVA'));
$('#reset').addEventListener('click',async()=>{if(viewMode!=='narrator')return;if(await confirmation('Recomeçar a cena? As rolagens e os turnos salvos serão reiniciados.')){if(await run(cmd('restart'),'CENA RECOMEÇADA')){maintenancePairId=null;rebuildSelectors();render();}}});
$('#evolve').addEventListener('click',()=>{
 const actor=selectedAlly(),pair=engine.pairOf(state,actor),human=selectedHuman();if(!canControl(actor.id))return;
 const highest=Object.entries(actor.forms).filter(([,f])=>f.unlocked).sort((a,b)=>engine.STAGES[b[1].stage].order-engine.STAGES[a[1].stage].order)[0]?.[0];
 const available=(id,f)=>id!==actor.formId&&f.unlocked&&pair.level>=engine.STAGES[f.stage].level&&(!(engine.STAGES[f.stage].order>engine.STAGES[engine.currentForm(actor).stage].order)||human.remaining>0&&!(pair.bond<0&&id===highest));
 formContext={kind:'evolution'};setText('actionTitle','EVOLUTION ACCESS');
 $('#actionFields').innerHTML='<p>Formas de teste. Evoluir usa a ação do Humano; Devolução voluntária não usa a ação do Digimon. O dano sofrido e os usos da forma são preservados.</p>'+select('cfgForm','FORMA',Object.entries(actor.forms).map(([id,f])=>`<option value="${id}" ${available(id,f)?'':'disabled'}>${escape(f.name)} · ${engine.STAGES[f.stage].label} // ${id===actor.formId?'ACTIVE':available(id,f)?'AVAILABLE':'LOCKED'}</option>`).join(''));
 $('#confirmAction').textContent='CONFIRMAR TRANSFORMAÇÃO';$('#confirmAction').disabled=!Object.entries(actor.forms).some(([id,f])=>available(id,f));$('#actionDialog').showModal();updatePreview();
});
function setLabMode(creating){
 $('#labTitle').textContent=creating?(npcSide==='ally'?'CRIAR ALIADO NPC / HUMANO':'CRIAR NPC INIMIGO'):'EDITAR PARTICIPANTE';
 $('#labForm button[type="submit"]').textContent=creating?'ADICIONAR NPC':'APLICAR AO CENÁRIO';
 for(const id of ['labScene','labActor','labFormId','labLevel','labBond','labEnergy','labHumanName','labTalents','labUnlocked','labActive'])$('#'+id).closest('label').hidden=creating&&!(npcSide==='ally'&&['labLevel','labBond','labEnergy','labHumanName','labTalents'].includes(id));
}
const galleryArts=[...sheetArt,{name:'Alphamon',image:'assets/alphamon.png'}];
let galleryChoices=null,galleryLoading=null;
async function renderLabGallery(){
 if(!$('#labGallery').open){$('#labArtGrid').replaceChildren();return;}
 if(!galleryChoices){setText('labArtStatus','Carregando nomes…');galleryLoading||=import('/creator/digimon-database.js').then(({digimonDatabase})=>{const names=new Map();for(const d of digimonDatabase){const cutout=sheetArt.find(a=>a.digibankId===d.id);names.set(d.id,{name:displayName(d.name),stage:d.stage,image:cutout?.image||(d.image.startsWith('./')?'/creator/'+d.image.slice(2):d.image)});}names.set('internal-alphamon',{name:'Alphamon (asset interno)',image:'assets/alphamon.png',stage:'mega'});return [...names.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));});try{galleryChoices=await galleryLoading;}catch{galleryLoading=null;setText('labArtStatus','Não foi possível carregar os nomes. Tente novamente.');return;}}
 if(!$('#labGallery').open)return;
 const query=fieldValue('labArtSearch').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),matches=galleryChoices.filter(art=>art.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query)),visible=matches.slice(0,40),chosen=fieldValue('labImageLink');
 $('#labArtGrid').replaceChildren(...visible.map(art=>{const button=document.createElement('button');const url=new URL(art.image,location.href).href;button.type='button';button.className='lab-art-choice name-only';button.textContent=art.name;button.setAttribute('aria-label','Usar imagem de '+art.name);button.setAttribute('aria-pressed',String(chosen===url));button.onclick=()=>{$('#labImage').value='';$('#labImageLink').value=url;$('#labArtPreview').src=url;setText('labArtStatus','Imagem selecionada: '+art.name+'. Salve para aplicar.');$('#labArtGrid').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));};return button;}));
 setText('labArtStatus',matches.length?'Exibindo '+visible.length+' de '+matches.length+' nomes. Pesquise para filtrar; a imagem carrega ao selecionar.':'Nenhum Digimon encontrado.');
}
$('#labGallery').addEventListener('toggle',renderLabGallery);
$('#labArtSearch').addEventListener('input',()=>{setText('labArtStatus','');renderLabGallery();});
$('#labImageLink').addEventListener('input',()=>{ $('#labImage').value='';setText('labArtStatus','');if(fieldValue('labImageLink'))$('#labArtPreview').src=fieldValue('labImageLink');renderLabGallery(); });
$('#labImage').addEventListener('change',async()=>{const file=$('#labImage').files[0];if(file?.type==='image/png'&&file.size<=12*1024*1024){$('#labImageLink').value='';$('#labArtPreview').src=await imageData(file);setText('labArtStatus','PNG escolhido: '+file.name);renderLabGallery();}});
function fillLab(rebuild=false){
 const labState=npcDraft||state,actor=engine.actorById(labState,fieldValue('labActor')),pair=engine.pairOf(labState,actor);
 if(rebuild){$('#labFormId').innerHTML=Object.entries(actor.forms).map(([id,f])=>option(id,engine.STAGES[f.stage].label+' // '+f.name)).join('');$('#labFormId').value=actor.formId;}
 const id=fieldValue('labFormId'),f=actor.forms[id]||engine.currentForm(actor);labFlipped=!!actor.flipped;$('#labArtPreview').src=f.image;$('#labArtPreview').style.transform=labFlipped?'scaleX(-1)':'';for(const [id,k] of [['labBody','body'],['labMind','mind'],['labPresence','presence']]){$('#'+id).closest('label').hidden=!pair;$('#'+id).value=pair?labState.humans.find(h=>h.pairId===pair.id).characteristics[k]:1;}
 $('#labImageLink').value=/^https?:\/\//i.test(f.image)?f.image:'';$('#labName').value=f.name;$('#labHumanName').value=pair?labState.humans.find(h=>h.pairId===pair.id).name:'';$('#labHumanName').disabled=!pair;$('#labQualities').value=f.qualities.map(q=>q.name+' | '+q.rank).join('\n');$('#labAttacks').value=f.attacks.map(a=>[a.name,a.rank,a.element,a.effect||a.sourceEffects?.[0]||''].join(' | ')).join('\n');$('#labStage').value=f.stage;$('#labElement').value=f.element;$('#labDigital').value=f.digitalAttribute;
 for(const key of Object.keys(engine.ATTRIBUTES))$('#lab'+key[0].toUpperCase()+key.slice(1)).value=f.attributes[key];
 $('#labHp').value=actor.hp;$('#labLevel').value=pair?.level||1;$('#labBond').value=pair?.bond||0;$('#labEnergy').value=pair?labState.humans.find(h=>h.pairId===pair.id).energy:0;
 $('#labTalents').disabled=!pair;$('#labTalents').value=pair?labState.humans.find(h=>h.pairId===pair.id).talents.map(t=>t.name+' | '+t.rank).join('\n'):'';
 $('#labUnlocked').checked=f.unlocked;$('#labActive').checked=id===actor.formId;$('#labX').value=actor.position.x;$('#labY').value=actor.position.y;$('#labScale').value=actor.position.scale;$('#labImage').value='';$('#labQualityChoice').value='';$('#labQualityRank').value=1;setText('labQualityStatus','');$('#labGallery').open=false;$('#labArtSearch').value='';setText('labArtStatus','');renderLabGallery();
 for(const id of Object.keys(engine.CONDITIONS))$('#condition-'+id).checked=!!actor.conditions[id];
 for(const id of ['labLevel','labBond','labEnergy'])$('#'+id).disabled=!pair;
 updateLabPreview();
}
function updateLabPreview(){try{
 const inputs=Object.keys(engine.ATTRIBUTES).map(key=>$('#lab'+key[0].toUpperCase()+key.slice(1))),attrs=Object.fromEntries(Object.keys(engine.ATTRIBUTES).map((key,i)=>[key,Number(inputs[i].value)]));
 const stage=fieldValue('labStage'),rule=NPC_ATTRIBUTE_RULES[stage],sum=Object.values(attrs).reduce((total,value)=>total+value,0),m=engine.markers({stage,attributes:attrs});
 if(npcDraft){
  for(const [i,input] of inputs.entries()){input.min=rule.min;input.max=Math.min(rule.max,rule.total-sum+Number(input.value));input.readOnly=stage==='baby';}
  $('#labHp').value=m.hp;$('#labHp').readOnly=true;
  let error='';try{validateNpcAttributes(stage,attrs);}catch(e){error=e.message;}
  $('#labForm button[type="submit"]').disabled=!!error;
  setText('labPreview',`${engine.STAGES[stage].label} · ${sum} / ${rule.total} pontos · ${rule.total-sum} restantes. Base ${rule.min}; máximo ${rule.max} por atributo. PV ${m.hp} · Dano ${m.damage} · Esquiva base ${m.dodge}d6 · Usos de assinatura ${stage==='baby'?0:attrs.intelligence}. ${error}`);
 }else{
  for(const input of inputs){input.min=1;input.max=12;input.readOnly=false;}$('#labHp').readOnly=false;$('#labForm button[type="submit"]').disabled=false;
  setText('labPreview',`PV máximo ${m.hp} · Dano ${m.damage} · Esquiva base ${m.dodge}d6 · Usos de assinatura ${stage==='baby'?0:attrs.intelligence}. Ajuste os PV atuais se necessário.`);
 }
 }catch{setText('labPreview','Configure os atributos.');if(npcDraft)$('#labForm button[type="submit"]').disabled=true;}}
$('#labStage').addEventListener('change',()=>{if(npcDraft){const rule=NPC_ATTRIBUTE_RULES[fieldValue('labStage')];for(const key of Object.keys(engine.ATTRIBUTES))$('#lab'+key[0].toUpperCase()+key.slice(1)).value=rule.min;}updateLabPreview();});
for(const key of Object.keys(engine.ATTRIBUTES))$('#lab'+key[0].toUpperCase()+key.slice(1)).addEventListener('input',e=>{if(!npcDraft||e.target.value==='')return;const rule=NPC_ATTRIBUTE_RULES[fieldValue('labStage')],others=Object.keys(engine.ATTRIBUTES).filter(k=>k!==key).reduce((sum,k)=>sum+numeric('lab'+k[0].toUpperCase()+k.slice(1)),0);e.target.value=Math.max(rule.min,Math.min(rule.max,rule.total-others,Math.trunc(Number(e.target.value))));updateLabPreview();});
$('#labQualityOptions').innerHTML=qualityOptions.map(name=>`<option value="${escape(name)}"></option>`).join('');
$('#addLabQuality').addEventListener('click',()=>{const name=fieldValue('labQualityChoice').trim(),rank=numeric('labQualityRank');if(!name)return;const lines=fieldValue('labQualities').split('\n').filter(line=>line.trim());if(lines.some(line=>line.split('|')[0].trim().toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))){setText('labQualityStatus','Esta qualidade já está na lista. Edite o rank abaixo.');return;}if(lines.length>=12){setText('labQualityStatus','Máximo de 12 qualidades.');return;}lines.push(name+' | '+rank);$('#labQualities').value=lines.join('\n');$('#labQualityChoice').value='';setText('labQualityStatus','Qualidade adicionada. Você também pode editar ou criar qualidades abaixo.');});

$('#labStage').innerHTML=Object.entries(engine.STAGES).map(([id,s])=>option(id,s.label)).join('');$('#labElement').innerHTML=ELEMENTS.map(e=>option(e,e)).join('');$('#labConditions').innerHTML=Object.entries(engine.CONDITIONS).map(([id,label])=>check('condition-'+id,label)).join('');
$('#openLab').addEventListener('click',()=>{npcDraft=null;setLabMode(false);$('#labActor').disabled=false;$('#labFormId').disabled=false;$('#labTitle').textContent='LOCAL LAB';rebuildSelectors();$('#labActor').value=selectedActor().id;$('#labScene').value=state.scene.name;$('#labFormId').innerHTML='';fillLab(true);$('#labDialog').showModal();});$('#cancelLab').addEventListener('click',()=>$('#labDialog').close());$('#labActor').addEventListener('change',()=>fillLab(true));$('#labFormId').addEventListener('change',()=>fillLab(false));$('#labForm').addEventListener('input',updateLabPreview);
$('#labForm').addEventListener('submit',async e=>{e.preventDefault();let image=null;try{const file=$('#labImage').files[0];if(file){if(file.type!=='image/png'||file.size>12*1024*1024)throw Error('Escolha um PNG de até 12 MB');image=await imageData(file);}const attrs={};for(const key of Object.keys(engine.ATTRIBUTES))attrs[key]=Number($('#lab'+key[0].toUpperCase()+key.slice(1)).value);if(npcDraft)validateNpcAttributes(fieldValue('labStage'),attrs);const actor=engine.actorById(npcDraft||state,fieldValue('labActor'));const config={actorId:actor.id,formId:fieldValue('labFormId'),name:fieldValue('labName'),stage:fieldValue('labStage'),element:fieldValue('labElement'),digitalAttribute:fieldValue('labDigital'),attributes:attrs,hp:numeric('labHp'),position:{x:numeric('labX'),y:numeric('labY'),scale:numeric('labScale')},unlocked:checked('labUnlocked'),active:checked('labActive'),image:image||fieldValue('labImageLink')||null,conditions:Object.keys(engine.CONDITIONS).filter(id=>checked('condition-'+id)),poisonPower:numeric('labPoison')};if(engine.pairOf(npcDraft||state,actor))Object.assign(config,{level:numeric('labLevel'),bond:numeric('labBond'),energy:numeric('labEnergy')});if(engine.pairOf(npcDraft||state,actor))config.talents=fieldValue('labTalents').split('\n').filter(l=>l.trim()).map((l,i)=>{const [name,rank]=l.split('|');return {id:'talent-'+i,name:name.trim(),rank:Number(rank)};});config.qualities=fieldValue('labQualities').split('\n').filter(l=>l.trim()).map((l,i)=>{const [name,rank]=l.split('|');return {id:'quality-'+i,name:name.trim(),rank:Number(rank)};});config.attacks=fieldValue('labAttacks').split('\n').filter(l=>l.trim()).map((l,i)=>{return npcSignature(l,i);});config.characteristics={body:numeric('labBody'),mind:numeric('labMind'),presence:numeric('labPresence')};config.humanName=fieldValue('labHumanName');if(config.image&&!/^https?:\/\//i.test(config.image)&&!/^data:image\/(png|jpeg|webp);base64,/i.test(config.image))throw Error('Use um link HTTP ou HTTPS.');state=await commit(npcDraft?'createNpc':'configureLab',config,...(npcDraft?[npcSide]:[]));state=await commit('presentation',{actorId:config.actorId,flipped:labFlipped,name:fieldValue('labScene').slice(0,70)||'Cena de Teste'});npcDraft=null;rebuildSelectors();$('#labDialog').close();message('Configuração aplicada. A cena continua local e fictícia.');render();}catch(error){setText('labPreview',error.message);}});
const locations={grid:'DIGITAL ARENA',ice:'FROZEN VALLEY',sunset:'ANCIENT RUINS',forest:'FOREST NODE',metro:'SIGNAL LOST // SUBWAY',city:'NIGHT DISTRICT'};
$('#environment').addEventListener('change',async()=>{if(await run(cmd('presentation',{environment:fieldValue('environment'),background:null}),'CENÁRIO SALVO'))applyScenePresentation();});
$('#backgroundFile').addEventListener('change',async()=>{const file=$('#backgroundFile').files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12*1024*1024){report(Error('Escolha PNG, JPG ou WebP de até 12 MB'));return;}await run(cmd('presentation',{background:await imageData(file)}),'FUNDO SALVO');applyScenePresentation();});$('#clearBackground').addEventListener('click',async()=>{await run(cmd('presentation',{background:null}),'FUNDO REMOVIDO');applyScenePresentation();});
function applyScenePresentation(){const environment=state.scene.environment||'grid';$('#environment').value=environment;$('#arena').dataset.environment=environment;setText('location',locations[environment]||'DIGITAL ARENA');const background=state.scene.background;applyBackdrop($('#arena'),background);$('#clearBackground').hidden=!background;}

render();

function actorPairFinalized(actor){return !!engine.pairOf(state,actor)?.turnFinalized;}
$('#addAlly').onclick=openSheetPicker;$('#openForum').onclick=openSheetPicker;$('#closeAlly').onclick=()=>$('#allyDialog').close();
function openSheetPicker(){if(busy||viewMode!=='narrator')return;$('#allyDialog').showModal();if(!$('#forumSheets').children.length)$('#loadForum').click();}
function openNpc(side){if(busy||viewMode!=='narrator')return;try{npcSide=side;npcDraft=draftNpc(state,side);setLabMode(true);const actor=npcDraft.actors.at(-1);$('#labScene').value=state.scene.name;$('#labActor').innerHTML=option(actor.id,'NOVO NPC');$('#labActor').value=actor.id;$('#labActor').disabled=true;$('#labFormId').disabled=true;fillLab(true);$('#labDialog').showModal();}catch(e){report(e);}}
$('#addEnemy').onclick=()=>openNpc('enemy');$('#createAllyNpc').onclick=()=>{$('#allyDialog').close();openNpc('ally');};
$('#flipSprite').onclick=()=>{labFlipped=!labFlipped;$('#labArtPreview').style.transform=labFlipped?'scaleX(-1)':'';};
$('#labDialog').addEventListener('close',()=>{npcDraft=null;rebuildSelectors();});
$('#removeActor').addEventListener('click',async()=>{if(await confirmation('Remover este participante do cenário de teste?'))try{state=await commit('removeParticipant',selectedActor().id);rebuildSelectors();render();}catch(e){report(e);}});
const formationViews=document.createElement('div');formationViews.className='formation-views';
for(const [label,end] of [['← VER ALIADOS',false],['VER INIMIGOS →',true]]){const button=document.createElement('button');button.textContent=label;button.addEventListener('click',()=>{const arena=$('#arena');arena.scrollTo({left:end?arena.scrollWidth:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});formationViews.append(button);}
const formationHint=document.createElement('small');formationHint.textContent='Use a barra horizontal da arena para percorrer equipes maiores.';formationViews.append(formationHint);$('#arena').after(formationViews);
rebuildSelectors();if(playerId&&state.actors.some(a=>a.id===playerId))$('#operator').value=playerId;applyScenePresentation();render();

function switchView(mode){viewMode=mode;if(mode==='player')$('#operator').value=playerId||state.actors.find(a=>a.side==='ally')?.id||'';render();message(mode==='player'?'JOGADOR // Controle somente sua dupla.':'NARRADOR // Scene Control disponível.');}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',async()=>{if(busy)return;if(b.dataset.view==='narrator'&&!narratorAuthorized){try{const response=await apiFetch('/api/narrator');narratorAuthorized=(await response.json()).authorized===true;}catch{}if(!narratorAuthorized){$('#narratorPassword').value='';setText('narratorError','');$('#narratorDialog').showModal();return;}}switchView(b.dataset.view);}));
$('#cancelNarrator').onclick=()=>$('#narratorDialog').close();$('#narratorDialog').addEventListener('close',()=>{$('#narratorPassword').value='';});
$('#narratorForm').onsubmit=async e=>{e.preventDefault();$('#unlockNarrator').disabled=true;try{const response=await apiFetch('/api/narrator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:fieldValue('narratorPassword')})});const result=await response.json();if(!response.ok||!result.authorized)throw Error(result.error||'Não foi possível liberar o acesso.');narratorAuthorized=true;$('#narratorPassword').value='';$('#narratorDialog').close();switchView('narrator');}catch(error){setText('narratorError',error.message);}finally{$('#unlockNarrator').disabled=false;}};

$('#toggleResult').addEventListener('click',()=>{const hidden=$('#resolutionPanel').classList.toggle('folded');$('#toggleResult').textContent=hidden?'VER RESULTADO':'RECOLHER RESULTADO';});

function renderResolutionQueue(){const entries=(state.resolutions||[]).filter(r=>r.round===state.round);$('#resolutionQueue').innerHTML=entries.map(r=>{const p=r.pending||r.result,c=p?.context;return '<button data-resolution="'+r.id+'" class="resolution-ticket '+(r.id===state.activeResolutionId?'selected':'')+'"><b>'+escape(c?c.actor.name+' → '+c.target.name:p?.name||'Ação')+'</b><span>'+escape(c?.signature?.name||p?.action||'Ataque comum')+'</span><small>'+(r.pending?(engine.awaitingMultiAttacks(state,r.pending)?'CONFIRMAR OS DOIS ATAQUES':r.pending.attackConfirmed===false?'REVISAR ATAQUE':r.pending.kind==='attack'&&!r.pending.dodge?'AGUARDANDO ESQUIVA':r.pending.defenseConfirmed===false?'REVISAR ESQUIVA':'APLICAR RESULTADO'):'✓ RESOLVIDO')+'</small></button>';}).join('');$('#resolutionQueue').querySelectorAll('button').forEach(b=>{b.disabled=busy;b.onclick=()=>{state=engine.selectResolution(state,b.dataset.resolution);render();};});setText('queueCount',engine.pendingResolutions(state).length+' PENDENTES');}
$('#humanObserve').onclick=async()=>{const human=selectedHuman(),coordinates=human.observedRound===state.round-1;if(await confirmation(coordinates?'Dar Coordenadas usa a ação do Humano. O próximo ataque do seu Digimon nesta rodada recebe +1d6. Confirmar?':'Observar usa a ação do Humano e libera Dar Coordenadas somente na próxima rodada. Confirmar?'))await run(cmd(coordinates?'giveCoordinates':'observe',human.id),coordinates?'COORDENADAS ENVIADAS':'OBSERVANDO');};


$('#loadForum').onclick=async()=>{if(viewMode!=='narrator'||busy)return;const button=$('#loadForum');button.disabled=true;setText('forumStatus','Lendo a lista pública de fichas aprovadas…');try{const response=await apiFetch('/api/forum/sheets'),data=await response.json();if(!response.ok)throw Error(data.error);$('#forumSheets').replaceChildren(...data.sheets.map(sheet=>{const b=document.createElement('button');b.textContent=sheet.title;b.onclick=()=>readForumSheet(sheet);return b;}));setText('forumStatus',data.sheets.length+' fichas públicas. Selecione para revisar e adicionar à cena local.');}catch(e){setText('forumStatus',e.message);}finally{button.disabled=false;}};
async function readForumSheet(sheet){if(viewMode!=='narrator'||busy)return;setText('forumStatus','Lendo '+sheet.title+'…');$('#forumSheets').querySelectorAll('button').forEach(b=>b.disabled=true);try{const response=await apiFetch('/api/forum/sheet?path='+encodeURIComponent(sheet.path)),data=await response.json();if(!response.ok)throw Error(data.error);const parsed=parsePublicSheet(data.html,{title:data.title,url:data.url}),form=parsed.forms.rookie;setText('forumStatus',[parsed.human.name+' / '+form.name,'Nível '+parsed.level+' · PV '+parsed.hp+' · Energia '+parsed.human.energy+' · PL '+parsed.bond,...parsed.warnings].join(' — '));$('#allyDialog').close();if(await confirmation('Adicionar '+parsed.human.name+' / '+form.name+' como aliado? Nível '+parsed.level+', PV '+parsed.hp+'. '+(parsed.warnings.length?'Confira: '+parsed.warnings.join(' '):'Leitura da ficha pública; nenhuma alteração será enviada ao fórum.'))){state=await commit('importParticipant',parsed);rebuildSelectors();$('#operator').value=state.actors.at(-1).id;render();message('Ficha pública adicionada à sessão local. Retrato e atributos importados.');}}catch(e){setText('forumStatus',e.message);}finally{$('#forumSheets').querySelectorAll('button').forEach(b=>b.disabled=false);}}

function renderIncoming(){const a=selectedActor(),h=state.humans.find(h=>h.pairId===a.pairId),entries=[...engine.incomingAttacks(state,a.id),...(h?engine.incomingAttacks(state,h.id):[])];const root=$('#incomingBanner');root.hidden=!entries.length||!canControl(a.id);root.replaceChildren();for(const entry of entries){const p=entry.pending,b=document.createElement('button');b.className='primary';b.textContent=engine.awaitingMultiAttacks(state,p)?'MULTI-ATTACK // AGUARDANDO SEGUNDO ATAQUE':p.attackConfirmed===false?'ATAQUE RECEBIDO // AGUARDANDO ATACANTE':!p.dodge?'⚡ ESQUIVAR AGORA // '+p.context.target.name:'REVISAR DEFESA // '+p.context.target.name;b.disabled=busy||p.attackConfirmed===false||engine.awaitingMultiAttacks(state,p);b.onclick=()=>{state=engine.selectResolution(state,entry.id);render();if(!p.dodge)openAction('dodge');else openCommands();};root.append(b);}const note=document.createElement('small');note.textContent='Resolva a defesa antes de iniciar um ataque com o participante atingido.';root.append(note);}
$('#editResources').onclick=()=>{if(viewMode!=='narrator'||busy)return;const a=selectedActor(),h=state.humans.find(h=>h.pairId===a.pairId),p=engine.pairOf(state,a);setText('resourceTitle','Recursos // '+engine.currentForm(a).name);$('#resourceHp').value=a.hp;$('#resourceHp').max=engine.markers(engine.currentForm(a)).hp;for(const id of ['resourceEnergy','resourceBond'])$('#'+id).closest('label').hidden=!h;if(h){$('#resourceEnergy').value=h.energy;$('#resourceEnergy').max=9+p.level;$('#resourceBond').value=p.bond;$('#resourceBond').max=p.level+5;}setText('resourceError','');$('#resourceDialog').showModal();};
$('#closeResources').onclick=()=>$('#resourceDialog').close();$('#resourceForm').onsubmit=async e=>{e.preventDefault();if(viewMode!=='narrator')return;try{state=await commit('adjustResources',{actorId:selectedActor().id,hp:numeric('resourceHp'),energy:numeric('resourceEnergy'),bond:numeric('resourceBond')});$('#resourceDialog').close();render();}catch(e){setText('resourceError',e.message);}};


// Presentation can be local, but combat always resumes from the saved server revision.
let refreshing=false;
async function refreshSavedScene(){if(refreshing||document.hidden||busy||document.querySelector('dialog[open]:not(#commandDialog)'))return;refreshing=true;try{const response=await apiFetch(sceneEndpoint);if(!response.ok)return;const saved=await response.json();if(!busy&&saved.revision>revision){state=saved.state;revision=saved.revision;playerId=saved.actorId;maintenanceChoices.clear();for(const [id,value] of Object.entries(saved.maintenance||{}))maintenanceChoices.set(id,value);maintenancePairId=null;rebuildSelectors();applyScenePresentation();render();}}catch{}finally{refreshing=false;}}
setInterval(refreshSavedScene,4000);window.addEventListener('focus',refreshSavedScene);

if(new URLSearchParams(location.search).get('narrator')==='1')document.querySelector('[data-view="narrator"]').click();

function mountTargetCards(){const select=$('#cfgTarget');if(!select)return;select.parentElement.hidden=true;const fieldset=document.createElement('fieldset');fieldset.className='target-picker';fieldset.innerHTML='<legend>ESCOLHA O ALVO</legend>';for(const option of select.options){const entity=engine.entityById(state,option.value),human=!!entity.characteristics,f=human?null:engine.currentForm(entity),label=document.createElement('label');label.className='target-card';const input=document.createElement('input');input.type='radio';input.name='targetCard';input.value=entity.id;input.checked=select.value===entity.id;input.required=true;const img=document.createElement('img');img.src=human?entity.image:f.image;img.alt='';const info=document.createElement('span');info.innerHTML='<small>'+(human?'HUMANO':'DIGIMON')+'</small><b>'+escape(engine.entityName(entity))+'</b><span>'+(human?'ENERGIA':'PV')+' '+engine.entityLife(entity)+' / '+(human?9+(engine.pairOf(state,entity)?.level||1):engine.markers(f).hp)+'</span>';input.addEventListener('change',()=>{select.value=input.value;updatePreview();});label.append(input,img,info);fieldset.append(label);}select.parentElement.after(fieldset);}
function openDigivice(){const human=selectedHuman(),pair=selectedPair();if(!human||!canControl(human.id))return;const options=digiviceOptions(human,pair.level);formContext={kind:'digivice'};setText('actionTitle','FUNÇÕES DO DIGIVICE');$('#actionFields').innerHTML='<p class="digivice-intro">Cada ativação usa a ação do Humano. Melhorias e usos são lidos da ficha e salvos nesta cena.</p>'+(options.error?'<p>'+escape(options.error)+'</p>':'')+'<div class="digivice-function-grid">'+['Booster','Protocolos Especiais','Scanner de Cards'].map((name,i)=>'<label class="digivice-function"><input type="radio" name="digiviceFunction" value="'+name+'" '+(i===2?'disabled':'')+' '+(i===0?'checked':'')+'><b>'+name+'</b><small>'+(i===0?(options.booster.rank?'Nível '+options.booster.rank+' · '+Math.max(0,options.booster.limit-options.booster.used)+' uso(s) restante(s)':'Não instalado'):i===1?(options.protocols.length+' protocolo(s) instalado(s)'):'Em breve · bloqueado')+'</small></label>').join('')+'</div><input type="hidden" id="cfgFunction" value="Booster"><div id="boosterFields">'+select('cfgBoosterKind','PRÓXIMA ROLAGEM DO PARCEIRO',option('attack','Ataque · Vantagem')+'<option value="dodge" '+(options.booster.rank<2?'disabled':'')+'>Esquiva · Vantagem (Nível 2+)</option>')+'</div><div id="protocolFields" hidden>'+select('cfgProtocol','PROTOCOLO INSTALADO',options.protocols.map(d=>'<option value="'+d.id+'" '+(d.used||d.error?'disabled':'')+'>'+escape(d.protocol+(d.detail?' — '+d.detail:'')+(d.used?' · Usado':d.error?' · Revisar ficha':''))+'</option>').join(''))+'</div>';document.querySelectorAll('[name="digiviceFunction"]').forEach(input=>input.onchange=()=>{$('#cfgFunction').value=input.value;updateDigivicePreview();});$('#confirmAction').textContent='ATIVAR · AÇÃO DO HUMANO';$('#actionDialog').showModal();updateDigivicePreview();}
function updateDigivicePreview(){const human=selectedHuman(),actor=selectedAlly(),o=digiviceOptions(human,selectedPair().level),booster=fieldValue('cfgFunction')==='Booster',protocol=o.protocols.find(d=>d.id===fieldValue('cfgProtocol'));$('#boosterFields').hidden=!booster;$('#protocolFields').hidden=booster;let unavailable=o.error||(!human.remaining?'Ação do Humano já utilizada.':'');if(engine.entityPending(state,actor.id)||engine.incomingAttacks(state,actor.id).some(r=>r.pending.dodge))unavailable='Aplique a rolagem pendente do parceiro primeiro.';if(booster){if(!o.booster.rank)unavailable='Booster não instalado na ficha.';else if(o.booster.used>=o.booster.limit)unavailable='Usos de Booster esgotados neste combate.';else if(actor.boosterNext)unavailable='Já há um Booster aguardando a próxima rolagem.';}else if(!protocol||protocol.used||protocol.error)unavailable=protocol?.error||'Nenhum protocolo disponível neste combate.';if(!serverDigivice&&!unavailable)unavailable='Ativação do Digivice temporariamente indisponível nesta cena.';const descriptions={'Troca de Elemento':'Altera o elemento do parceiro e dos ataques de assinatura para '+protocol?.element+'.','Reforço de PV':'+10 PV atuais e máximos; esses 10 PV desaparecem ao terminar o efeito.','Reforço de Esquiva':'+1d6 na Esquiva.','Reforço de Dano':'+2 no dano base.','Qualidade Temporária':'Qualidade '+protocol?.quality+' de Rank 2.','Ataque Temporário':'Ataque '+protocol?.attack?.name+' no maior Rank dos ataques da forma atual.'};setText('configPreview',unavailable||(booster?'Vantagem na próxima rolagem de '+(fieldValue('cfgBoosterKind')==='dodge'?'Esquiva':'Ataque')+' do parceiro. Não gasta PL nem a ação do Digimon.':(descriptions[protocol.protocol]+' Dura até concluir a próxima ação do Digimon. Uma ativação deste protocolo por combate.')));$('#confirmAction').disabled=!!unavailable;}
$('#humanDigivice').addEventListener('click',openDigivice);

$('#labAttackElement').innerHTML=ELEMENTS.map(e=>option(e,e)).join('');
$('#labAttackEffect').innerHTML=option('','Sem efeito')+effectOptions.map(e=>option(e.name,displayName(e.name)+(automaticEffects.includes(npcSignature('A | 1 | Neutro | '+e.name).effect)?'':' · Narrador'))).join('');
function showNpcEffect(){const effect=effectOptions.find(e=>e.name===fieldValue('labAttackEffect'));setText('labAttackEffectHelp',effect?effect.description+(npcSignature('A | 1 | Neutro | '+effect.name).effect?'':' Aplicação manual pelo Narrador.'): 'Escolha um efeito para consultar a regra.');}
$('#labAttackEffect').addEventListener('change',showNpcEffect);showNpcEffect();
$('#addLabAttack').onclick=()=>{const name=fieldValue('labAttackName').trim();if(!name||name.includes('|')){setText('labAttackEffectHelp','Informe um nome para o ataque, sem o caractere |.');return;}const line=[name,fieldValue('labAttackRank'),fieldValue('labAttackElement'),fieldValue('labAttackEffect')].join(' | ');$('#labAttacks').value=[$('#labAttacks').value.trim(),line].filter(Boolean).join('\n');$('#labAttackName').value='';setText('labAttackEffectHelp','Ataque adicionado. Salve o NPC para aplicar.');updateLabPreview();};
