import {STAGES,ATTRIBUTES,CHARACTERISTICS,CONDITIONS,markers,elementalRelation,digitalBonus} from './rules.mjs';
import {rollPool} from './dice.mjs';
import {conditionMode,afterAction} from './conditions.mjs';
import {spendBond,loseBond,spendEnergy,rescue} from './resources.mjs';
import {currentForm,changeForm,evolve,maintain,highestForm} from './evolution.mjs';
import {initialBattle} from './fixtures.mjs';
export {initialBattle};
export {markers,STAGES,ATTRIBUTES,CHARACTERISTICS,CONDITIONS,currentForm};
export const actorById=(s,id)=>s.actors.find(a=>a.id===id);
export const entityById=(s,id)=>s.actors.find(a=>a.id===id)||s.humans.find(h=>h.id===id);
export const entityName=e=>e.characteristics?e.name:currentForm(e).name;
export const entityLife=e=>e.characteristics?e.energy:e.hp;
export const entitySide=(s,e)=>e.side||s.actors.find(a=>a.pairId===e.pairId)?.side;
export const humanById=(s,id)=>s.humans.find(h=>h.id===id);
export const pairOf=(s,entity)=>s.pairs.find(p=>p.id===entity.pairId);
const copy=s=>structuredClone(s);
const integer=(n,min=0,max=100)=>{if(!Number.isInteger(n)||n<min||n>max)throw Error('Valor inválido');return n;};
function available(s,entity){if(!entity)throw Error('Combatente indisponível');if(s.pending||s.phase!=='open'||pairOf(s,entity)?.turnFinalized)throw Error('Resolva a ação atual primeiro');if(entity.remaining<=0)throw Error('Ação bloqueada');if(entity.hp===0||entity.energy===0)throw Error('Combatente fora de combate');}
function addLog(s,entry){s.log.push({id:s.log.length+1,round:s.round,...entry});s.result=entry;}
function snapshotActor(actor){if(actor.characteristics)return {name:actor.name,stage:'human',element:'Neutro',attributes:{power:actor.characteristics.body},digitalAttribute:'Unknown'};const f=currentForm(actor);return {name:f.name,stage:f.stage,element:f.element,attributes:f.attributes,digitalAttribute:f.digitalAttribute};}
const effectKey=(signature,targetId)=>['atordoador','venenoso'].includes(signature.effect)?`${signature.effect}:${targetId}`:`${signature.id}:${targetId}:${signature.effect}`;
function extras(mode,relation=0){if(!['normal','advantage','disadvantage'].includes(mode||'normal'))throw Error('Modificador inválido');return {advantages:[...(mode==='advantage'?['Circunstância']:[]),...(relation===1?['Elemento']:[])],disadvantages:[...(mode==='disadvantage'?['Circunstância']:[]),...(relation===-1?['Elemento']:[])]};}
function selected(list,id){if(!id)return null;const item=list.find(q=>q.id===id);if(!item)throw Error('Opção indisponível nesta forma');return item;}
function knockOut(s,actor){if(actor.hp>0)return;actor.remaining=0;actor.defending=false;actor.conditions.incapacitated={};const f=currentForm(actor);if(!['baby','rookie'].includes(f.stage)){const base=Object.keys(actor.forms).find(id=>actor.forms[id].stage==='rookie');if(base){changeForm(actor,base,{floor:false});actor.hp=0;addLog(s,{kind:'devolution',summary:`${f.name}: 0 PV. Devolução; fora de combate. O narrador determina as consequências.`,actorId:actor.id});}}}
function endAction(s,actor){afterAction(actor);if(actor.conditions.poisoned){const power=actor.conditions.poisoned.power||0,old=actor.hp;const save=rescue(pairOf(s,actor),old-power,actor.rescueEnabled);actor.hp=save.value;addLog(s,{kind:'condition',summary:`Veneno: ${old} → ${actor.hp} PV${save.cost?' · Força para Lutar: −3 PL':''}`,actorId:actor.id});knockOut(s,actor);}}
function consume(s,actor){actor.remaining--;actor.defending=false;if(actor.conditions.stunned){delete actor.conditions.stunned;addLog(s,{kind:'stunned',summary:`${currentForm(actor).name} perdeu a próxima ação: Atordoado.`,actorId:actor.id});endAction(s,actor);return true;}return false;}
export function attackPreview(s,config){const actor=config.entityType==='human'?humanById(s,config.actorId):actorById(s,config.actorId),target=entityById(s,config.targetId);if(actor?.characteristics)return humanAttackPreview(s,config);if(!actor||!target||actor.id===target.id||entitySide(s,actor)===entitySide(s,target)||!entityLife(target))throw Error('Alvo indisponível');const f=currentForm(actor),tf=target.characteristics?snapshotActor(target):currentForm(target);if(!(config.attribute in ATTRIBUTES))throw Error('Escolha um atributo');const quality=selected(f.qualities,config.qualityId),signature=selected(f.attacks,config.signatureId);const bond=integer(config.bond||0,0,30);const relation=elementalRelation(signature?.element||f.element,tf.element),mod=conditionMode(actor,'attack',extras(config.mode,relation));const pool=f.attributes[config.attribute]+(quality?.rank||0)+(signature?.rank||0)+bond;
 const guidanceBonus=actor.coordinatesRound===s.round?1:0;
 const effectAlreadyUsed=signature&&actor.effectTargets.includes(effectKey(signature,target.id));
 return {actorId:actor.id,targetId:target.id,actor:snapshotActor(actor),target:snapshotActor(target),attribute:config.attribute,quality,signature,bond,pool:pool+guidanceBonus,guidanceBonus,mode:mod.mode,reasons:mod,element:signature?.element||f.element,targetType:target.characteristics?'human':'digimon',digitalBonus:target.characteristics?0:digitalBonus(f,tf),baseDamage:markers(f).damage,weak:!!actor.conditions.weak,description:String(config.description||'').slice(0,1000),extraUse:!!config.extraUse,useEffect:!!config.useEffect&&!effectAlreadyUsed,effectAlreadyUsed};
}
export function beginAttack(s,config,random=undefined){const n=copy(s),actor=config.entityType==='human'?humanById(n,config.actorId):actorById(n,config.actorId);available(n,actor);const context=attackPreview(n,config);actor.rescueEnabled=!!config.rescueEnabled;if(actor.characteristics){actor.remaining--;if(config.effort)spendEnergy(actor,1);}else if(consume(n,actor))return n;const pair=pairOf(n,actor);if(context.bond)spendBond(pair,context.bond);let extraCost=0,useCost=0;
 if(context.signature){const sig=context.signature,id=actor.formId,key=sig.id;const efficient=sig.effect==='eficiente'&&!actor.usedAttacks.includes(key);if(!efficient){if((actor.uses[id]||0)<=0){if(!config.extraUse)throw Error('Usos esgotados: ative Segura Essa!');spendBond(pair,1);extraCost=1;}else{actor.uses[id]--;useCost=1;}}actor.usedAttacks.push(key);}
 if(context.guidanceBonus)delete actor.coordinatesRound;
 n.pending={kind:'attack',phase:config.staged?'attack-review':'await-dodge',reviewFlow:!!config.staged,attackConfirmed:!config.staged,defenseConfirmed:!config.staged,context,attack:rollPool(context.pool,context.mode,random),dodge:null,attackForced:false,dodgeForced:false,costs:{attackBond:context.bond+extraCost,signatureUses:useCost,dodgeBond:0},rescueEnabled:config.rescueEnabled===true};
 addLog(n,{kind:'attack-roll',actorId:actor.id,summary:`${context.actor.name} → ${context.target.name}: ${context.signature?.name||'Ataque comum'} · ${context.pool}d6 · ${ATTRIBUTES[context.attribute]||CHARACTERISTICS[context.attribute]}${context.quality?' + '+context.quality.name+' '+context.quality.rank:''}`,roll:n.pending.attack,costs:n.pending.costs,context});return n;
}
export function dodgePreview(s,config){if(s.pending?.kind!=='attack'||s.pending.dodge||s.pending.attackConfirmed===false)throw Error('Nenhuma esquiva pendente');const target=entityById(s,s.pending.context.targetId),human=!!target.characteristics,f=human?null:currentForm(target),quality=selected(human?target.talents:f.qualities,config.qualityId),bond=integer(config.bond||0,0,30),mod=conditionMode({...target,conditions:target.conditions||{}},'dodge',extras(config.mode));return {pool:(human?target.characteristics.body:markers(f).dodge)+(quality?.rank||0)+bond,mode:mod.mode,reasons:mod,quality,bond};}
export function rollDodge(s,config,random=undefined){const n=copy(s),spec=dodgePreview(n,config),target=entityById(n,n.pending.context.targetId);if(spec.bond)spendBond(pairOf(n,target),spec.bond);n.pending.dodge=rollPool(spec.pool,spec.mode,random);n.pending.dodgeSpec=spec;n.pending.costs.dodgeBond=spec.bond;n.pending.rescueEnabled=!!config.rescueEnabled;n.pending.phase='review';addLog(n,{kind:'dodge-roll',actorId:target.id,summary:`${entityName(target)}: Esquiva ${spec.pool}d6 · Agilidade + estágio${spec.quality?' + '+spec.quality.name:''}`,roll:n.pending.dodge,costs:{bond:spec.bond}});return n;}
export function attackResult(pending){if(!pending?.dodge)throw Error('Role a esquiva antes de resolver');const difference=pending.attack.successes-pending.dodge.successes,hit=pending.attack.successes>0&&difference>=0;const c=pending.context;let heavy=hit&&c.signature?.effect==='pesado'?1+c.signature.rank:0;let raw=hit?c.baseDamage+difference+c.digitalBonus+heavy:0;if(hit&&c.weak)raw=Math.ceil(raw/2);let effect=null;if(hit&&c.useEffect){if(['atordoador','venenoso'].includes(c.signature?.effect))raw=0;else if(['enfraquecedor','quebra-bloqueio'].includes(c.signature?.effect))raw=Math.ceil(raw/2);effect=c.signature?.effect;}if(hit&&c.signature?.effect==='desorientador')effect='desorientador';return {hit,outcome:hit?'HIT CONFIRMED':'DODGE SUCCESSFUL',difference,base:c.baseDamage,digital:c.digitalBonus,heavy,weak:c.weak,damage:raw,effect};}
export function forceTest(s,side,random=undefined){const n=copy(s),p=n.pending;if(!p)throw Error('Nenhum teste para forçar');let entity,roll;
 if(p.kind==='attack'){if(p.reviewFlow&&p.defenseConfirmed)throw Error('Esquiva já confirmada.');if(p.reviewFlow&&!p.attackConfirmed){if(side!=='attack'||p.attackForced)throw Error('Rolagem já forçada ou lado indisponível');entity=entityById(n,p.context.actorId);roll=p.attack;p.attackForced=true;}else{if(!p.dodge)throw Error('Conclua o teste oposto');const r=attackResult(p);if(side==='attack'){if(p.reviewFlow||r.hit||p.attackForced)throw Error('Ataque não pode ser forçado');entity=p.context.entityType==='human'?humanById(n,p.context.actorId):actorById(n,p.context.actorId);roll=p.attack;p.attackForced=true;}else if(side==='dodge'){if(!r.hit||p.dodgeForced)throw Error('Esquiva não pode ser forçada');entity=entityById(n,p.context.targetId);roll=p.dodge;p.dodgeForced=true;}else throw Error('Lado inválido');}}
 else{if(p.roll.successes>=p.difficulty||p.forced)throw Error('Teste não pode ser forçado');entity=p.entityType==='human'?humanById(n,p.entityId):actorById(n,p.entityId);roll=p.roll;p.forced=true;}
 const pair=pairOf(n,entity);if(!pair)throw Error('NPC sem parceria: não possui Pontos de Laço para perder');loseBond(pair,2);const retry={...rollPool(roll.pool,roll.mode,random),forced:true};if(p.kind==='attack')p[side==='attack'?'attack':'dodge']=retry;else p.roll=retry;addLog(n,{kind:'forced',actorId:entity.id,summary:`Forçar ${side==='dodge'?'Esquiva':'Teste'}: −2 PL (perda), mesmo grupo ${roll.pool}d6. Uma tentativa extra.`,roll:retry});return n;
}
export function acceptResult(s){const n=copy(s),p=n.pending;if(!p)throw Error('Nenhum resultado pendente');if(p.reviewFlow&&!p.defenseConfirmed)throw Error('O defensor precisa aceitar a esquiva.');if(p.reviewFlow&&p.dodge&&!p.survivalDecided){const t=entityById(n,p.context.targetId);if(attackResult(p).damage>=entityLife(t)&&entityLife(t)>0&&pairOf(n,t)?.bond>=3)throw Error('Decida sobre Força para Lutar antes de aplicar o dano.');}n.pending=null;
 if(p.kind==='attack'){const r=attackResult(p),actor=p.context.entityType==='human'?humanById(n,p.context.actorId):actorById(n,p.context.actorId),target=entityById(n,p.context.targetId),humanTarget=!!target.characteristics,old=entityLife(target);const save=rescue(pairOf(n,target),old-r.damage,p.rescueEnabled);if(humanTarget)target.energy=save.value;else target.hp=save.value;let applied=null;target.conditions||={};const effects={atordoador:'stunned',desorientador:'disoriented',enfraquecedor:'weak','quebra-bloqueio':'vulnerable',venenoso:'poisoned',imobilizador:'immobilized'};if(r.effect&&effects[r.effect]){const key=effectKey(p.context.signature,target.id);actor.effectTargets||=[];if(!actor.effectTargets.includes(key)){applied=effects[r.effect];target.conditions[applied]=applied==='poisoned'?{power:p.context.actor.attributes.power}:{};actor.effectTargets.push(key);}}
 const result={kind:'attack',actorId:actor.id,targetId:target.id,context:p.context,attack:p.attack,dodge:p.dodge,...r,effectApplied:applied,hpBefore:old,hpAfter:entityLife(target),actualDamage:Math.max(0,old-entityLife(target)),costs:{...p.costs,rescueBond:save.cost},summary:r.hit?`${p.context.actor.name} usou ${p.context.signature?.name||'Ataque comum'} em ${p.context.target.name} e causou ${r.damage} de dano${save.cost?' · Força para Lutar: −3 PL, permaneceu com 1':''}.`:`${p.context.actor.name} usou ${p.context.signature?.name||'Ataque comum'} em ${p.context.target.name} e errou o ataque.`};addLog(n,result);if(!actor.characteristics)endAction(n,actor);if(humanTarget){if(!target.energy)target.remaining=0;}else knockOut(n,target);n.result=result;
 }else{const entity=p.entityType==='human'?humanById(n,p.entityId):actorById(n,p.entityId),success=p.roll.successes>=p.difficulty;const result={...p,actorId:entity.id,kind:'test',success,outcome:success?'SUCCESS':'FAIL',summary:`${p.name}: ${p.action} · ${p.roll.successes}/${p.difficulty} sucessos · ${success?'SUCCESS':'FAIL'}. ${p.description||''}`};addLog(n,result);if(p.entityType==='digimon')endAction(n,entity);}
 return n;
}
export function defend(s,id,options={}){const n=copy(s),actor=actorById(n,id);available(n,actor);actor.rescueEnabled=options.rescueEnabled??actor.rescueEnabled;if(consume(n,actor))return n;actor.defending=true;addLog(n,{kind:'defend',actorId:id,summary:`${currentForm(actor).name}: postura defensiva. Vantagem na Esquiva até a próxima oportunidade de agir.`});endAction(n,actor);return n;}
export function genericTest(s,config,random=undefined){
 const n=copy(s),isHuman=config.entityType==='human',entity=isHuman?humanById(n,config.entityId):actorById(n,config.entityId);available(n,entity);
 if(!isHuman)entity.rescueEnabled=!!config.rescueEnabled;
 const stats=isHuman?entity.characteristics:currentForm(entity).attributes,labels=isHuman?CHARACTERISTICS:ATTRIBUTES;
 if(!(config.attribute in labels))throw Error('Característica inválida');
 const bonus=selected(isHuman?entity.talents:currentForm(entity).qualities,config.qualityId),bond=integer(config.bond||0,0,30),effort=!!config.effort,difficulty=integer(config.difficulty,1,12);
 if(effort&&!isHuman)throw Error('Esforço é exclusivo do Humano');
 if(isHuman)entity.remaining--;else if(consume(n,entity))return n;
 const pair=pairOf(n,entity);if(bond)spendBond(pair,bond);let rescueCost=0;
 if(effort){spendEnergy(entity,1);const save=rescue(pair,entity.energy,config.rescueEnabled);entity.energy=save.value;rescueCost=save.cost;}
 const mode=isHuman?(config.mode||'normal'):conditionMode(entity,'test',extras(config.mode)).mode,pool=stats[config.attribute]+(bonus?.rank||0)+bond+(effort?1:0);
 n.pending={kind:'test',phase:'review',entityType:config.entityType,entityId:entity.id,name:isHuman?entity.name:currentForm(entity).name,action:String(config.action||'Interagir'),attribute:config.attribute,quality:bonus,description:String(config.description||'').slice(0,1000),roll:rollPool(pool,mode,random),difficulty,forced:false,costs:{bond:bond+rescueCost,energy:effort?1:0}};addLog(n,{kind:'test-roll',actorId:entity.id,summary:`${n.pending.name}: ${n.pending.action} · ${pool}d6 · dificuldade ${difficulty}`,roll:n.pending.roll,costs:n.pending.costs});return n;
}
export function evolveAction(s,actorId,id){const n=copy(s),actor=actorById(n,actorId),pair=pairOf(n,actor),human=n.humans.find(h=>h.pairId===actor.pairId);if(!pair||!human||!actor.hp)throw Error('Parceria indisponível');const higher=STAGES[actor.forms[id]?.stage]?.order>STAGES[currentForm(actor).stage].order;if(n.pending||n.phase!=='open'||pair.turnFinalized)throw Error('Cena bloqueada');if(higher)available(n,human);const before=currentForm(actor).name,result=evolve(actor,human,pair,id);if(result.higher)human.remaining--;addLog(n,{kind:'evolution',actorId,summary:`${result.higher?'EVOLUÇÃO':'DEVOLUÇÃO'}: ${before} ${result.higher?'digivolve':'retorna'} para… ${currentForm(actor).name}!`,costs:{energy:0,bondLoss:result.bondLoss},hpAfter:actor.hp});return n;}
export function multiAttack(s,entityType,id){const n=copy(s),entity=entityType==='human'?humanById(n,id):actorById(n,id);if(!entity||entity.remaining>0||entity.multiUsed||n.pending||n.phase!=='open'||pairOf(n,entity)?.turnFinalized||entity.hp===0||entity.energy===0)throw Error('Ação adicional indisponível');spendBond(pairOf(n,entity),2);entity.remaining=1;entity.multiUsed=true;entity.defending=false;addLog(n,{kind:'multi',summary:'Multi-Attack: −2 PL, 1 ação adicional; uma vez neste turno.',actorId:id,costs:{bond:2}});return n;}
export function skipAction(s,entityType,id,options={}){const n=copy(s),entity=entityType==='human'?humanById(n,id):actorById(n,id);available(n,entity);if(entityType==='human'){entity.remaining=0;entity.skipped=true;}else{entity.rescueEnabled=options.rescueEnabled??entity.rescueEnabled;const stunned=consume(n,entity);entity.remaining=0;if(!stunned)endAction(n,entity);}addLog(n,{kind:'skip',summary:`${entityType==='human'?entity.name:currentForm(entity).name}: ação dispensada.`,actorId:id});return n;}
export function playerComplete(s,pairId=null){return s.actors.filter(a=>a.controller==='player'&&(!pairId||a.pairId===pairId)).every(a=>a.remaining===0||a.hp===0)&&s.humans.filter(h=>!pairId||h.pairId===pairId).every(h=>h.remaining===0||h.energy===0)&&!s.pending;}
export function finalizeTurn(s,text,pairId=s.pairs[0]?.id){const pair=s.pairs.find(p=>p.id===pairId);if(!pair||!playerComplete(s,pairId)||pair.turnFinalized)throw Error('Conclua as ações da dupla');const n=copy(s),ids=[...n.actors,...n.humans].filter(e=>e.pairId===pairId).map(e=>e.id);n.narratives.push({round:n.round,pairId,text:String(text||'').slice(0,12000),mechanics:n.log.filter(e=>e.round===n.round&&ids.includes(e.actorId)&&['attack','test','evolution','defend','skip','stunned'].includes(e.kind)).map(e=>e.summary)});n.pairs.find(p=>p.id===pairId).turnFinalized=true;n.turnFinalized=n.pairs.every(p=>p.turnFinalized);addLog(n,{kind:'narrative',pairId,summary:'TURN COMPLETE // Narrativa da dupla guardada somente nesta sessão local.'});return n;}
export function closeRound(s,options={}){if(s.pending||s.phase!=='open'||!s.turnFinalized||s.actors.some(a=>a.remaining>0&&a.hp>0)||s.humans.some(h=>h.remaining>0&&h.energy>0))throw Error('Finalize a dupla e resolva/dispense os NPCs antes de encerrar a rodada');const n=copy(s);for(const pair of n.pairs){const actor=n.actors.find(a=>a.pairId===pair.id),human=n.humans.find(h=>h.pairId===pair.id);if(!actor||!human||!actor.hp)continue;const before=currentForm(actor).name,cost=maintain(actor,human,pair,options[pair.id]||{});addLog(n,{kind:'maintenance',actorId:actor.id,costs:cost,summary:cost.devolved?`${before}: manutenção recusada/indisponível. Devolveu para ${currentForm(actor).name}; custo 0.`:`Manutenção ${before}: −${cost.energy} Energia / −${cost.bond} PL${human.energy===0?' · Humano fora de combate.':''}`});if(human.energy===0)human.remaining=0;}n.phase='closed';return n;}
export function nextRound(s){if(s.phase!=='closed')throw Error('Encerre a rodada para aplicar manutenção');const n=copy(s);n.round++;n.phase='open';n.turnFinalized=false;for(const p of n.pairs)p.turnFinalized=false;n.result=null;for(const a of n.actors){a.remaining=a.hp?1:0;a.multiUsed=false;a.defending=false;}for(const h of n.humans){h.remaining=h.energy?1:0;h.multiUsed=false;h.skipped=false;}addLog(n,{kind:'round',summary:`ROUND ${String(n.round).padStart(2,'0')} // Nova oportunidade de agir.`});return n;}
export function configureLab(s,config){if(s.pending||s.phase!=='open'||s.log.length)throw Error('Edite o LAB antes de agir; reinicie para reconfigurar');const n=copy(s),actor=actorById(n,config.actorId);if(!actor)throw Error('Combatente inválido');const f=actor.forms[config.formId||actor.formId];if(!f)throw Error('Forma inválida');if(config.stage){if(!STAGES[config.stage])throw Error('Estágio inválido');f.stage=config.stage;}if(config.name)f.name=String(config.name).slice(0,70);if(config.attributes)for(const key of Object.keys(ATTRIBUTES))f.attributes[key]=integer(config.attributes[key],1,12);if(config.element){if(!['Fogo','Madeira','Água/Gelo','Elétrico','Vento','Terra','Luz','Escuridão','Metal','Neutro'].includes(config.element))throw Error('Elemento inválido');f.element=config.element;}if(config.digitalAttribute)f.digitalAttribute=config.digitalAttribute;if(config.unlocked!==undefined)f.unlocked=!!config.unlocked;if(config.image)f.image=config.image;actor.position={...actor.position,...config.position};actor.rescueEnabled=!!config.rescueEnabled;
 if(config.qualities){if(config.qualities.length>12)throw Error('Máximo de 12 qualidades');f.qualities=config.qualities.map(q=>({id:String(q.id),name:String(q.name).trim().slice(0,70),rank:integer(q.rank,1,3)}));if(f.qualities.some(q=>!q.name))throw Error('Nome da qualidade obrigatório');}
 if(config.attacks){if(config.attacks.length>12)throw Error('Máximo de 12 ataques');f.attacks=config.attacks.map(a=>{if(!String(a.name).trim()||!['Fogo','Madeira','Água/Gelo','Elétrico','Vento','Terra','Luz','Escuridão','Metal','Neutro'].includes(a.element)||a.effect&&!['eficiente','pesado','atordoador','venenoso','enfraquecedor','quebra-bloqueio','desorientador','imobilizador'].includes(a.effect))throw Error('Ataque ou efeito inválido');return {...a,id:String(a.id),name:String(a.name).trim().slice(0,70),rank:integer(a.rank,1,4)};});}
 if(config.active){actor.formId=config.formId||actor.formId;f.unlocked=true;}actor.hp=integer(config.hp??markers(currentForm(actor)).hp,0,markers(currentForm(actor)).hp);actor.uses[actor.formId]=currentForm(actor).attributes.intelligence;actor.conditions={};for(const id of config.conditions||[]){if(!CONDITIONS[id])throw Error('Condição inválida');actor.conditions[id]=id==='poisoned'?{power:integer(config.poisonPower??2,1,12)}:{};}
 const pair=pairOf(n,actor);if(pair){if(config.level!==undefined)pair.level=integer(config.level,1,10);if(config.bond!==undefined)pair.bond=integer(config.bond,-20,pair.level+5);const human=n.humans.find(h=>h.pairId===pair.id);if(config.characteristics)for(const key of Object.keys(CHARACTERISTICS))human.characteristics[key]=integer(config.characteristics[key],1,12);if(config.humanName)human.name=String(config.humanName).trim().slice(0,70);if(config.talents){if(config.talents.length>12)throw Error('Máximo de 12 talentos no LAB');human.talents=config.talents.map(t=>({id:String(t.id),name:String(t.name).slice(0,70),rank:integer(t.rank,1,6)}));if(human.talents.some(t=>!t.name.trim()))throw Error('Nome do talento obrigatório');}human.energy=integer(config.energy??Math.min(human.energy,9+pair.level),0,9+pair.level);human.remaining=human.energy?1:0;}
 for(const [key,min,max] of [['x',-160,160],['y',-80,80],['scale',.4,1.5]])if(!Number.isFinite(actor.position[key])||actor.position[key]<min||actor.position[key]>max)throw Error('Posição ou escala inválida');
 actor.highestReached=actor.formId===highestForm(actor);actor.remaining=actor.hp?1:0;return n;}

export function humanAttackPreview(s,config){const human=humanById(s,config.actorId),target=entityById(s,config.targetId);if(!human||!target||!entityLife(target))throw Error('Alvo indisponível');const linked=s.actors.find(a=>a.pairId===human.pairId);if(linked?.side===entitySide(s,target))throw Error('Escolha um adversário');const talent=selected(human.talents,config.qualityId),bond=integer(config.bond||0,0,30),mod=extras(config.mode);return {entityType:'human',actorId:human.id,targetId:target.id,targetType:target.characteristics?'human':'digimon',actor:{name:human.name,attributes:{power:human.characteristics.body}},target:snapshotActor(target),attribute:'body',quality:talent,signature:null,bond,pool:human.characteristics.body+(talent?.rank||0)+bond+(config.effort?1:0),mode:mod.advantages.length?'advantage':mod.disadvantages.length?'disadvantage':'normal',reasons:mod,element:'Neutro',digitalBonus:0,baseDamage:1,weak:false,description:String(config.description||'').slice(0,1000),useEffect:false};}
export function addParticipant(s,side){if(s.log.length||s.pending||s.phase!=='open')throw Error('Configure as equipes antes de agir');if(!['ally','enemy'].includes(side))throw Error('Equipe inválida');if(s.actors.filter(a=>a.side===side).length>=5)throw Error('Máximo de 5 combatentes por lado');const n=copy(s),template=initialBattle(),index=Array.from({length:5},(_,i)=>i+1).find(i=>!n.actors.some(a=>a.id===side+'-'+i)),id=side+'-'+index,actor=structuredClone(template.actors.find(a=>a.side===side));actor.id=id;for(const f of Object.values(actor.forms))f.name+=' '+index;actor.position={x:0,y:0,scale:1};if(side==='ally'){const pair=structuredClone(template.pairs[0]);pair.id='pair-'+id;pair.turnFinalized=false;actor.pairId=pair.id;const human=structuredClone(template.humans[0]);human.id='human-'+id;human.pairId=pair.id;human.name='Operador de Teste '+index;n.humans.push(human);n.pairs.push(pair);}n.actors.push(actor);return n;}
export function removeParticipant(s,id){if(s.log.length||s.pending||s.phase!=='open')throw Error('Configure as equipes antes de agir');const actor=actorById(s,id);if(!actor||s.actors.filter(a=>a.side===actor.side).length<=1)throw Error('Mantenha pelo menos um combatente de cada lado');const n=copy(s);n.actors=n.actors.filter(a=>a.id!==id);if(actor.pairId){n.humans=n.humans.filter(h=>h.pairId!==actor.pairId);n.pairs=n.pairs.filter(p=>p.id!==actor.pairId);}return n;}
