import {roundStatus,partnershipStatus} from './round-status.mjs';
export {roundStatus,partnershipStatus} from './round-status.mjs';
// Resolution queue and live scene membership wrap the existing combat engine.
// Dice, damage, costs, effects and evolution still come from engine.mjs.
import * as core from './engine.mjs';
import {illustrateExample} from './example-art.mjs';
export * from './engine.mjs';
export function exampleBattle(){const s=core.initialBattle();s.actors.forEach((a,i)=>illustrateExample(s,a,i));return s;}
export function emptyBattle(){const s=exampleBattle();s.actors=[];s.humans=[];s.pairs=[];s.log=[];s.scene={name:'Nova cena',environment:'grid',background:null,audio:false};return s;}
export const pendingResolutions=s=>(s.resolutions||[]).filter(r=>r.pending);
export const entityPending=(s,id)=>pendingResolutions(s).some(r=>(r.pending.context?.actorId||r.pending.entityId)===id);
export function importParticipant(s,data){if(s.actors.some(a=>a.source?.url===data.source.url))throw Error('Esta ficha já está na cena.');const n=addParticipant(s,'ally'),a=n.actors.at(-1),h=n.humans.find(h=>h.pairId===a.pairId),p=core.pairOf(n,a);Object.assign(a,{forms:structuredClone(data.forms),formId:'rookie',hp:data.hp,uses:{rookie:data.forms.rookie.attributes.intelligence},source:data.source,importWarnings:data.warnings,highestReached:Object.keys(data.forms).length===1});Object.assign(h,structuredClone(data.human));Object.assign(p,{level:data.level,bond:data.bond});n.log.at(-1).summary=`${h.name} / ${core.currentForm(a).name}: ficha pública importada para esta sessão.`;return n;}
export function cancelResolution(s,id){const n=structuredClone(s),entry=n.resolutions.find(r=>r.id===id);if(!entry?.pending)throw Error('Resolução indisponível');entry.result={...entry.pending,kind:'canceled',summary:'Resolução cancelada pelo Narrador. A ação e os recursos gastos não são devolvidos.'};entry.pending=null;n.log.push({id:n.log.length+1,round:n.round,kind:'canceled',actorId:entry.result.context?.actorId||entry.result.entityId,summary:entry.result.summary});if(n.activeResolutionId===id){n.pending=null;n.result=entry.result;}return n;}
const queue=s=>structuredClone(s.resolutions||[]);
function start(s,fn,id,continuation=false){if(entityPending(s,id)&&!continuation)throw Error('Este participante ainda tem uma ação aguardando resolução');const n=fn({...s,pending:null});n.resolutions=queue(s);if(n.pending){const entry={id:'action-'+(n.log.length),round:n.round,pending:structuredClone(n.pending),result:null};n.resolutions.push(entry);n.activeResolutionId=entry.id;}else{n.pending=s.pending;n.activeResolutionId=s.activeResolutionId;}return n;}
export const incomingAttacks=(s,id)=>pendingResolutions(s).filter(r=>r.pending.kind==='attack'&&r.pending.context.targetId===id);
export function canContinueMulti(s,id){const a=core.entityById(s,id),entries=pendingResolutions(s).filter(r=>(r.pending.context?.actorId||r.pending.entityId)===id);return !!(s.phase==='open'&&a&&core.entityLife(a)>0&&!core.pairOf(s,a)?.turnFinalized&&a.remaining===1&&a.multiUsed&&entries.length===1&&entries[0].pending.multiGroup&&entries[0].pending.attackConfirmed&&!entries[0].pending.dodge);}
export function awaitingMultiAttacks(s,p=s.pending){if(!p?.multiGroup)return false;const a=core.entityById(s,p.context.actorId);return !!(a?.remaining||pendingResolutions(s).some(r=>r.pending.multiGroup===p.multiGroup&&r.pending.attackConfirmed===false));}
export const beginAttack=(s,c,r)=>{if(incomingAttacks(s,c.actorId).length)throw Error('Resolva primeiro o ataque direcionado a você.');const continuation=canContinueMulti(s,c.actorId),group=continuation?pendingResolutions(s).find(r=>r.pending.context?.actorId===c.actorId).pending.multiGroup:null;const n=start(s,n=>core.beginAttack(n,c,r),c.actorId,continuation);if(group&&n.pending){n.pending.multiGroup=group;n.resolutions.find(r=>r.id===n.activeResolutionId).pending=structuredClone(n.pending);}return n;};
export function confirmAttack(s){if(!s.pending?.reviewFlow||s.pending.attackConfirmed)throw Error('Ataque já confirmado.');return revise(s,n=>{const next=structuredClone(n);next.pending.attackConfirmed=true;next.pending.phase='await-dodge';return next;});}
// Group two independently reviewed attacks before releasing their dodge reactions.
export function canAcceptAttackMulti(s){const p=s.pending,a=core.entityById(s,p?.context?.actorId),pair=a&&core.pairOf(s,a);return !!(p?.kind==='attack'&&p.attackConfirmed===false&&a&&core.entitySide(s,a)==='ally'&&core.entityLife(a)>0&&!a.remaining&&!a.multiUsed&&pair&&!pair.turnFinalized&&pair.bond>=2&&s.phase==='open');}
export function confirmAttackMulti(s){if(!canAcceptAttackMulti(s))throw Error('Multi-Attack indisponível: exige 2 PL e só pode ser usado uma vez por turno.');const confirmed=confirmAttack(s),id=confirmed.pending.context.actorId,type=confirmed.pending.context.entityType==='human'?'human':'digimon';const n=core.multiAttack({...confirmed,pending:null},type,id);n.pending=structuredClone(confirmed.pending);n.pending.multiGroup=n.activeResolutionId;n.resolutions.find(r=>r.id===n.activeResolutionId).pending=structuredClone(n.pending);return n;}
export function confirmDodge(s){if(!s.pending?.dodge||s.pending.defenseConfirmed)throw Error('Esquiva indisponível.');return revise(s,n=>{const next=structuredClone(n);next.pending.defenseConfirmed=true;next.pending.phase='review';return next;});}
export function survivalOffer(s){const p=s.pending;if(p?.kind!=='attack'||!p.dodge||p.survivalDecided)return null;const target=core.entityById(s,p.context.targetId),pair=core.pairOf(s,target);return core.attackResult(p).damage>=core.entityLife(target)&&core.entityLife(target)>0&&pair?.bond>=3?{id:target.id,name:core.entityName(target),resource:target.characteristics?'Energia':'PV'}:null;}
export function decideSurvival(s,use){if(!survivalOffer(s))throw Error('Força para Lutar indisponível.');return revise(s,n=>{const next=structuredClone(n);next.pending.survivalDecided=true;next.pending.rescueEnabled=!!use;return next;});}
export const genericTest=(s,c,r)=>{return start(s,n=>core.genericTest(n,c,r),c.entityId);};
function revise(s,fn){const n=fn(s);n.resolutions=queue(s);const entry=n.resolutions.find(r=>r.id===s.activeResolutionId);if(entry)entry.pending=structuredClone(n.pending);return n;}
export const rollDodge=(s,c,r)=>{if(awaitingMultiAttacks(s))throw Error('Aguarde os dois ataques do Multi-Attack serem confirmados.');return revise(s,n=>core.rollDodge(n,c,r));};
export const forceTest=(s,c,r)=>revise(s,n=>core.forceTest(n,c,r));
export function selectResolution(s,id){const n=structuredClone(s),entry=n.resolutions?.find(r=>r.id===id);if(!entry)throw Error('Resolução indisponível');n.activeResolutionId=id;n.pending=structuredClone(entry.pending);n.result=structuredClone(entry.result);return n;}
export function acceptResult(s){const n=core.acceptResult(s);n.resolutions=queue(s);const entry=n.resolutions.find(r=>r.id===s.activeResolutionId);if(entry){entry.pending=null;entry.result=structuredClone(n.result);}return n;}
function immediate(s,fn,id){if(entityPending(s,id))throw Error('Resolva a ação deste participante primeiro');const n=fn({...s,pending:null});n.pending=structuredClone(s.pending);return n;}
export const defend=(s,id,o)=>{if(incomingAttacks(s,id).some(r=>r.pending.dodge))throw Error('Aplique a esquiva já rolada antes de declarar Defesa.');return immediate(s,n=>core.defend(n,id,o),id);};
export const skipAction=(s,t,id,o)=>{return immediate(s,n=>core.skipAction(n,t,id,o),id);};
export const multiAttack=(s,t,id)=>{return immediate(s,n=>core.multiAttack(n,t,id),id);};
export function evolveAction(s,id,f){const a=core.actorById(s,id),h=s.humans.find(h=>h.pairId===a?.pairId),ids=[id,h?.id];if(entityPending(s,h?.id)||pendingResolutions(s).some(r=>ids.includes(r.pending.context?.targetId)))throw Error('Resolva as ações envolvendo esta dupla antes de evoluir');return immediate(s,n=>core.evolveAction(n,id,f),id);}
export function humanWait(s,id,action='Aguardar'){if(!['Aguardar','Observar'].includes(action))throw Error('Ação inválida');const n=skipAction(s,'human',id),human=core.humanById(n,id),entry=n.log.at(-1);entry.summary=`${human.name}: ${action.toLowerCase()}, sem rolagem e sem custo.`;entry.action=action;human.lastAction=action;return n;}
export function observe(s,id){const h=core.humanById(s,id);if(!h||h.observedRound===s.round||h.observedRound===s.round-1)throw Error('Observação indisponível nesta rodada.');const n=humanWait(s,id,'Observar');core.humanById(n,id).observedRound=s.round;n.log.at(-1).summary+=' Dar Coordenadas disponível na rodada '+(s.round+1)+'.';return n;}
export function giveCoordinates(s,id){const h=core.humanById(s,id),a=s.actors.find(a=>a.pairId===h?.pairId);if(!h||h.observedRound!==s.round-1||h.coordinatesUsedRound===s.round||!a?.hp)throw Error('Observe na rodada anterior para dar coordenadas.');if(entityPending(s,a.id))throw Error('Aplique o ataque pendente antes de dar coordenadas.');const n=skipAction(s,'human',id),human=core.humanById(n,id),actor=core.actorById(n,a.id);human.coordinatesUsedRound=s.round;human.lastAction='Dar Coordenadas';actor.coordinatesRound=s.round;n.log.at(-1).summary=`${human.name}: coordenadas enviadas. Próximo ataque de ${core.currentForm(actor).name} nesta rodada recebe +1d6.`;return n;}
export function pairPending(s,pairId){const ids=[...s.actors,...s.humans].filter(a=>a.pairId===pairId).map(a=>a.id);return pendingResolutions(s).some(r=>ids.includes(r.pending.context?.actorId||r.pending.entityId)||ids.includes(r.pending.context?.targetId));}
export function playerComplete(s,pairId=null){return pairId?partnershipStatus(s,pairId).complete:!roundStatus(s).pending&&s.pairs.every(p=>partnershipStatus(s,p.id).complete);}
export function finalizeTurn(s,_text='',id=s.pairs[0]?.id){if(!playerComplete(s,id))throw Error('Conclua as ações e resoluções desta dupla.');const n=structuredClone(s),p=n.pairs.find(p=>p.id===id);if(!p)throw Error('Dupla indisponível');p.turnFinalized=true;n.log.push({id:n.log.length+1,round:n.round,kind:'turn-complete',pairId:id,summary:'Turno da dupla concluído. A narração acontece no fórum.'});return n;}
export function closeRound(s,o){const status=roundStatus(s);if(!status.ready)throw Error(status.pending?'Resolva as '+status.pending+' resoluções pendentes.':'Faltam ações: '+status.waiting.map(u=>u.name+' ('+u.type+')').join(', '));const n=structuredClone(s);n.pending=null;n.turnFinalized=true;for(const p of n.pairs)p.turnFinalized=true;return core.closeRound(n,o);}
export function nextRound(s){const n=core.nextRound(s);n.pending=null;n.activeResolutionId=null;for(const h of n.humans)delete h.lastAction;return n;}
function sceneLog(n,kind,actorId,summary){n.log.push({id:n.log.length+1,round:n.round,kind,actorId,summary});n.turnFinalized=n.pairs.every(p=>p.turnFinalized);return n;}
export function addParticipant(s,side){const n=core.addParticipant({...s,log:[],pending:null,phase:'open'},side);n.log=structuredClone(s.log);n.pending=structuredClone(s.pending);n.phase=s.phase;const a=n.actors.at(-1);if(s.log.some(entry=>entry.actorId===a.id)){let i=1;while(n.actors.some(x=>x.id===side+'-'+i)||s.log.some(x=>x.actorId===side+'-'+i))i++;a.id=side+'-'+i;const oldPair=a.pairId;if(oldPair){const p=n.pairs.find(p=>p.id===oldPair),h=n.humans.find(h=>h.pairId===oldPair);a.pairId='pair-'+a.id;p.id=a.pairId;h.pairId=a.pairId;h.id='human-'+a.id;}}if(s.phase==='closed'){a.remaining=0;const h=n.humans.find(h=>h.pairId===a.pairId);if(h)h.remaining=0;}illustrateExample(n,a,s.actors.length);return sceneLog(n,'arrival',a.id,`${core.currentForm(a).name} entrou na cena.`);}
export function removeParticipant(s,id){const actor=core.actorById(s,id);if(!actor)throw Error('Participante indisponível');const human=s.humans.find(h=>h.pairId===actor.pairId),ids=[id,human?.id];if(pendingResolutions(s).some(r=>ids.includes(r.pending.context?.actorId||r.pending.entityId)||ids.includes(r.pending.context?.targetId)))throw Error('Resolva as ações envolvendo este participante antes de retirá-lo');const n=structuredClone(s);n.actors=n.actors.filter(a=>a.id!==id);if(actor.pairId){n.humans=n.humans.filter(h=>h.pairId!==actor.pairId);n.pairs=n.pairs.filter(p=>p.id!==actor.pairId);}n.log=structuredClone(s.log);n.pending=structuredClone(s.pending);n.phase=s.phase;return sceneLog(n,'departure',id,`${core.currentForm(actor).name} saiu da cena.`);}
export function configureLab(s,c){const actor=core.actorById(s,c.actorId),human=s.humans.find(h=>h.pairId===actor?.pairId),ids=[c.actorId,human?.id];if(pendingResolutions(s).some(r=>ids.includes(r.pending.context?.actorId||r.pending.entityId)||ids.includes(r.pending.context?.targetId)))throw Error('Resolva as ações envolvendo o participante antes de editá-lo');const n=core.configureLab({...s,pending:null,log:[],phase:'open'},c);n.log=structuredClone(s.log);n.pending=structuredClone(s.pending);n.phase=s.phase;const edited=core.actorById(n,actor.id);for(const key of ['remaining','multiUsed','usedAttacks','effectTargets','defending'])edited[key]=structuredClone(actor[key]);if(s.log.some(e=>!['arrival','departure','scene-edit'].includes(e.kind))){edited.uses=structuredClone(actor.uses);edited.highestReached=actor.highestReached;}const before=s.humans.find(h=>h.pairId===actor.pairId),after=n.humans.find(h=>h.pairId===actor.pairId);if(before&&after)for(const key of ['remaining','multiUsed','skipped'])after[key]=before[key];return sceneLog(n,'scene-edit',actor.id,`${core.currentForm(actor).name}: configuração local atualizada pelo Narrador.`);}

export function restartScene(s){const n=structuredClone(s);Object.assign(n,{round:1,phase:'open',pending:null,result:null,resolutions:[],activeResolutionId:null,log:[],narratives:[],turnFinalized:false});for(const p of n.pairs)p.turnFinalized=false;for(const a of n.actors){delete a.coordinatesRound;Object.assign(a,{remaining:a.hp>0?1:0,multiUsed:false,usedAttacks:[],effectTargets:[],defending:false,uses:{[a.formId]:core.currentForm(a).attributes.intelligence}});}for(const h of n.humans){delete h.observedRound;delete h.coordinatesUsedRound;delete h.lastAction;Object.assign(h,{remaining:h.energy>0?1:0,multiUsed:false,skipped:false});}return n;}
