import test from 'node:test';import assert from 'node:assert/strict';import * as e from './scene-engine.mjs';
import {conditionHelp} from './condition-help.mjs';import {conditionMode} from './conditions.mjs';
import {approvedLinks,readApproved} from './forum-service.mjs';
const high=()=>.99,low=()=>0;
const attack=(s,id,target='enemy')=>e.beginAttack(s,{actorId:id,targetId:target,attribute:'power',bond:0,mode:'normal'},high);
test('three attacks await independent manual dodges; reserved actions cannot be reused',()=>{let s=e.initialBattle();s=e.addParticipant(s,'ally');s=e.addParticipant(s,'ally');for(const id of ['ally','ally-1','ally-2'])s=attack(s,id);assert.equal(e.pendingResolutions(s).length,3);assert.equal(s.actors.find(a=>a.id==='enemy').hp,17);assert.throws(()=>attack(s,'ally'));const ids=s.resolutions.map(r=>r.id);s=e.selectResolution(s,ids[1]);s=e.rollDodge(s,{},high);s=e.acceptResult(s);assert.equal(e.pendingResolutions(s).length,2);assert.equal(s.resolutions[1].pending,null);assert.ok(s.resolutions[1].result);assert.equal(s.resolutions[0].pending.dodge,null);assert.throws(()=>e.closeRound(s));s=e.cancelResolution(s,ids[0]);assert.equal(e.pendingResolutions(s).length,1);assert.equal(s.actors[0].remaining,0);});
test('human wait and observe consume only human action without costs or dice during another queued attack',()=>{for(const action of ['Aguardar','Observar']){let s=attack(e.initialBattle(),'ally');const energy=s.humans[0].energy,bond=s.pairs[0].bond;s=e.humanWait(s,'human-1',action);assert.equal(s.humans[0].remaining,0);assert.equal(s.humans[0].energy,energy);assert.equal(s.pairs[0].bond,bond);assert.equal(e.pendingResolutions(s).length,1);assert.equal(s.log.at(-1).action,action);assert.throws(()=>e.humanWait(s,'human-1'));}});
test('live roster changes preserve rolls and spending; pending involvement must resolve or cancel',()=>{let s=attack(e.initialBattle(),'ally');s=e.addParticipant(s,'ally');s=e.addParticipant(s,'enemy');assert.equal(e.pendingResolutions(s).length,1);assert.equal(s.actors[0].remaining,0);assert.throws(()=>e.removeParticipant(s,'ally'));s=e.removeParticipant(s,'enemy-1');assert.equal(e.pendingResolutions(s).length,1);assert.equal(s.actors[0].remaining,0);});
test('live lab edits never refund actions or signatures',()=>{let s=e.defend(e.initialBattle(),'ally');s=e.humanWait(s,'human-1');s.actors[0].uses.rookie=1;s=e.configureLab(s,{actorId:'ally',name:'Nome atualizado',hp:14});assert.equal(s.actors[0].remaining,0);assert.equal(s.humans[0].remaining,0);assert.equal(s.actors[0].uses.rookie,1);assert.equal(s.log.length,3);});
test('narrator round closure and next round restore availability after all pairs finish',()=>{let s=e.initialBattle();s=e.skipAction(s,'digimon','ally');s=e.humanWait(s,'human-1','Observar');s=e.skipAction(s,'digimon','enemy');assert.equal(e.roundStatus(s).ready,true);s=e.nextRound(e.closeRound(s));assert.equal(s.round,2);assert.equal(s.actors[0].remaining,1);assert.equal(s.humans[0].remaining,1);assert.equal(s.narratives.length,0);});
test('conditions have help and incapacitated/desoriented automatically change appropriate pools',()=>{for(const id of Object.keys(e.CONDITIONS))assert.ok(conditionHelp[id]);let s=e.initialBattle();s.actors[0].conditions.incapacitated={};assert.equal(conditionMode(s.actors[0],'dodge').mode,'disadvantage');s.actors[0].conditions.disoriented={};assert.equal(e.attackPreview(s,{actorId:'ally',targetId:'enemy',attribute:'power'}).mode,'disadvantage');});
test('approved links filter same-origin topic titles; no arbitrary server fetch paths',()=>{const list=approvedLinks('<a class="topictitle" href="/t43-f-kurogane-koga">Kōga</a><a class="topictitle" href="https://evil.example/t43-f-koga">wrong</a><a href="/t1-unrelated">other</a>');assert.equal(list.length,1);assert.equal(list[0].title,'Kōga');});

test('round checklist identifies unused human action and blocks unresolved queue',()=>{let s=e.initialBattle();s=e.skipAction(s,'digimon','ally');s=e.skipAction(s,'digimon','enemy');assert.equal(e.roundStatus(s).waiting[0].type,'Humano');assert.throws(()=>e.closeRound(s),/Humano/);s=e.humanWait(s,'human-1');assert.equal(e.roundStatus(s).ready,true);assert.equal(e.partnershipStatus(s,'pair-1').label,'TURNO CONCLUÍDO');let q=attack(e.initialBattle(),'ally');q=e.humanWait(q,'human-1');q=e.skipAction(q,'digimon','enemy');assert.equal(e.roundStatus(q).pending,1);assert.equal(e.roundStatus(q).ready,false);assert.throws(()=>e.closeRound(q),/resoluções/);q=e.cancelResolution(q,q.resolutions[0].id);assert.equal(e.roundStatus(q).ready,true);assert.equal(e.nextRound(e.closeRound(q)).round,2);});
