/* Transparent cutouts from the site Digibank: occupied Rookie partners only. */
export const sheetArt=[
  {
    "id": "kudamon",
    "digibankId": "rookie-kudamon",
    "name": "Kudamon",
    "partner": "Kailen Dur",
    "stage": "rookie",
    "element": "Luz",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/kudamon.png",
    "source": "https://digimon.net/cimages/digimon/kudamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/kudamon.jpg",
    "sourceSha256": "c73bd3f2ff07b4f5110639abaca5d93c1ca4455f77c2344a96b5122363c44b89",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 804690,
    "visiblePixels": 767826,
    "bounds": {
      "x": 0,
      "y": 23,
      "width": 1127,
      "height": 1231
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "coronamon",
    "digibankId": "rookie-coronamon",
    "name": "Coronamon",
    "partner": "Takeshi Shiba",
    "stage": "rookie",
    "element": "Fogo",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/coronamon.png",
    "source": "https://digimon.net/cimages/digimon/coronamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/coronamon.jpg",
    "sourceSha256": "6271bc6108c22011d7483b3296ebfa9ac8b94375380c1d3809a0a846f41cff2e",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1015738,
    "visiblePixels": 556778,
    "bounds": {
      "x": 21,
      "y": 10,
      "width": 1215,
      "height": 1230
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "hyokomon",
    "digibankId": "rookie-hyokomon",
    "name": "Hyokomon",
    "partner": "Haruka Nagasawa",
    "stage": "rookie",
    "element": "Vento",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/hyokomon.png",
    "source": "https://digimon.net/cimages/digimon/hyokomon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/hyokomon.jpg",
    "sourceSha256": "926e355d6ba58b78ea5e63baf362ae31a5d99fdb75e9aa251075f4b0d96a13a8",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 943049,
    "visiblePixels": 629467,
    "bounds": {
      "x": 130,
      "y": 0,
      "width": 1104,
      "height": 1245
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "biyomon",
    "digibankId": "rookie-biyomon",
    "name": "Biyomon",
    "partner": "Mei Shuyan",
    "stage": "rookie",
    "element": "Fogo",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/biyomon.png",
    "source": "https://digimon.net/cimages/digimon/piyomon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/piyomon.jpg",
    "sourceSha256": "d64b2d510947fb205e30de27dcfa3ea9d174280584923f8a265937114692b76c",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1078305,
    "visiblePixels": 494211,
    "bounds": {
      "x": 59,
      "y": 17,
      "width": 1167,
      "height": 1237
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "falcomon",
    "digibankId": "rookie-falcomon",
    "name": "Falcomon",
    "partner": "Hattori Hanzo",
    "stage": "rookie",
    "element": "Vento",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/falcomon.png",
    "source": "https://digimon.net/cimages/digimon/falcomon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/falcomon.jpg",
    "sourceSha256": "abdd4f7492ef46bcac584ae559dcd259833155b9b4b3c62538c4f242b522c413",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1075960,
    "visiblePixels": 496556,
    "bounds": {
      "x": 0,
      "y": 24,
      "width": 1224,
      "height": 1206
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "salamon",
    "digibankId": "rookie-salamon",
    "name": "Salamon",
    "partner": "Setsuka Kaneko",
    "stage": "rookie",
    "element": "Luz",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/salamon.png",
    "source": "https://digimon.net/cimages/digimon/plotmon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/plotmon.jpg",
    "sourceSha256": "fd6f99950a7d9f22b12594f75f9d98853478f9041aa83112dc6dca09d67af84c",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 885854,
    "visiblePixels": 686662,
    "bounds": {
      "x": 29,
      "y": 30,
      "width": 1199,
      "height": 1194
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "ryudamon",
    "digibankId": "rookie-ryudamon",
    "name": "Ryudamon",
    "partner": "Amakuza Ryuken",
    "stage": "rookie",
    "element": "Metal",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/ryudamon.png",
    "source": "https://digimon.net/cimages/digimon/ryudamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/ryudamon.jpg",
    "sourceSha256": "790f78d865731ea2842ab5df1c1c560882059443cd2ae74dae1b1b6afb05dc6a",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 988049,
    "visiblePixels": 584467,
    "bounds": {
      "x": 0,
      "y": 37,
      "width": 1224,
      "height": 1217
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "gaomon",
    "digibankId": "rookie-gaomon",
    "name": "Gaomon",
    "partner": "Taiga Amagiri",
    "stage": "rookie",
    "element": "Vento",
    "digitalAttribute": "Data",
    "image": "assets/partners/gaomon.png",
    "source": "https://digimon.net/cimages/digimon/gaomon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/gaomon.jpg",
    "sourceSha256": "1f5fbabfc711a7d9143ab95b2f9fb2d8e85fa63b759222d125aea42e1e277b69",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1145432,
    "visiblePixels": 427084,
    "bounds": {
      "x": 0,
      "y": 7,
      "width": 1253,
      "height": 1247
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "gabumon",
    "digibankId": "rookie-gabumon",
    "name": "Gabumon",
    "partner": "Kiyomasa",
    "stage": "rookie",
    "element": "Água",
    "digitalAttribute": "Data",
    "image": "assets/partners/gabumon.png",
    "source": "https://digimon.net/cimages/digimon/gabumon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/gabumon.jpg",
    "sourceSha256": "03657b79bda018ba649847cd4b2ce2691b457132fc9eed8ba506de06ba87f904",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 937365,
    "visiblePixels": 635151,
    "bounds": {
      "x": 53,
      "y": 25,
      "width": 1177,
      "height": 1229
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "black-gabumon",
    "digibankId": "rookie-black-gabumon",
    "name": "Black Gabumon",
    "partner": "Kajima Satoru",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/black-gabumon.png",
    "source": "https://digimon.net/cimages/digimon/gabumon_black.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/gabumon_black.jpg",
    "sourceSha256": "7340a4da9cc920e5d841e14c2dd37235312b8363324932f80a27178885b5b12f",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 902362,
    "visiblePixels": 670154,
    "bounds": {
      "x": 35,
      "y": 17,
      "width": 1203,
      "height": 1237
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "patamon",
    "digibankId": "rookie-patamon",
    "name": "Patamon",
    "partner": "Nagi Kurose",
    "stage": "rookie",
    "element": "Vento",
    "digitalAttribute": "Data",
    "image": "assets/partners/patamon.png",
    "source": "https://i.ibb.co/GwwHRtB/image.png",
    "sourceImage": "https://i.ibb.co/GwwHRtB/image.png",
    "sourceSha256": "3742db43982c602939841d8e9a413693520f852177bcc9316cbcfec4a6feb317",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 938962,
    "visiblePixels": 633554,
    "bounds": {
      "x": 0,
      "y": 39,
      "width": 1226,
      "height": 1181
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "huckmon",
    "digibankId": "rookie-huckmon",
    "name": "Huckmon",
    "partner": "Mikazuchi Yuki",
    "stage": "rookie",
    "element": "Metal",
    "digitalAttribute": "Data",
    "image": "assets/partners/huckmon.png",
    "source": "https://digimon.net/cimages/digimon/huckmon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/huckmon.jpg",
    "sourceSha256": "567b641a42bc5af68ca36549dd419abbcd3dc28e94633e2363ed51a7c915e1e4",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1025576,
    "visiblePixels": 546940,
    "bounds": {
      "x": 23,
      "y": 22,
      "width": 1219,
      "height": 1192
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "lalamon",
    "digibankId": "rookie-lalamon",
    "name": "Lalamon",
    "partner": "Keiko Ibara",
    "stage": "rookie",
    "element": "Madeira",
    "digitalAttribute": "Data",
    "image": "assets/partners/lalamon.png",
    "source": "https://digimon.net/cimages/digimon/lalamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/lalamon.jpg",
    "sourceSha256": "788a14d92bc8d98e42ee7f77b085e3ae193bcdfb30cc979753b2b9cd3ce1c536",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1031081,
    "visiblePixels": 541435,
    "bounds": {
      "x": 0,
      "y": 24,
      "width": 1236,
      "height": 1230
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "lunamon",
    "digibankId": "rookie-lunamon",
    "name": "Lunamon",
    "partner": "Nagasawa Miyuki",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Data",
    "image": "assets/partners/lunamon.png",
    "source": "https://digimon.net/cimages/digimon/lunamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/lunamon.jpg",
    "sourceSha256": "9e6874f9bce704379fa4304b8c68e1011dfaa73fed7c0ac089730c0bac5c033f",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 875243,
    "visiblePixels": 697273,
    "bounds": {
      "x": 33,
      "y": 1,
      "width": 1189,
      "height": 1253
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "renamon",
    "digibankId": "rookie-renamon",
    "name": "Renamon",
    "partner": "Shirogane Kai",
    "stage": "rookie",
    "element": "Luz",
    "digitalAttribute": "Data",
    "image": "assets/partners/renamon.png",
    "source": "https://digimon.net/cimages/digimon/renamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/renamon.jpg",
    "sourceSha256": "6a1deb36f661f633954d2f43a4a40977a1e7d1deaba31908ae091f8d7a4f3341",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1137049,
    "visiblePixels": 435467,
    "bounds": {
      "x": 25,
      "y": 16,
      "width": 1201,
      "height": 1228
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "lopmon",
    "digibankId": "rookie-lopmon",
    "name": "Lopmon",
    "partner": "Alice Hanegawa",
    "stage": "rookie",
    "element": "Terra",
    "digitalAttribute": "Data",
    "image": "assets/partners/lopmon.png",
    "source": "https://digimon.net/cimages/digimon/lopmon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/lopmon.jpg",
    "sourceSha256": "72bc4204d366e623c8bc79eb58cba361ffa908f53b8bfce903a641ccf023b2a1",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 947897,
    "visiblePixels": 624619,
    "bounds": {
      "x": 0,
      "y": 0,
      "width": 1248,
      "height": 1254
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "impmon",
    "digibankId": "rookie-impmon",
    "name": "Impmon",
    "partner": "Saori Yomikawa",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/impmon.png",
    "source": "https://digimon.net/cimages/digimon/impmon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/impmon.jpg",
    "sourceSha256": "5b1554bac1ea30b1d712fb4c248be05c1f609f4af1a57d6072a3a03fccaf8922",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1039467,
    "visiblePixels": 533049,
    "bounds": {
      "x": 0,
      "y": 55,
      "width": 1226,
      "height": 1199
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "otamamon",
    "digibankId": "rookie-otamamon",
    "name": "Otamamon",
    "partner": "Umi Tsukiume",
    "stage": "rookie",
    "element": "Água",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/otamamon.png",
    "source": "https://digimon.net/cimages/digimon/otamamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/otamamon.jpg",
    "sourceSha256": "abdbaddeef3a912de23b4f8cb41c10a2bf136746d0e4d8cdfc70558f070441e0",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1043613,
    "visiblePixels": 528903,
    "bounds": {
      "x": 0,
      "y": 31,
      "width": 1238,
      "height": 1197
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "gazimon",
    "digibankId": "rookie-gazimon",
    "name": "Gazimon",
    "partner": "Kurosawa Shin",
    "stage": "rookie",
    "element": "Elétrico",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/gazimon.png",
    "source": "https://digimon.net/cimages/digimon/gazimon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/gazimon.jpg",
    "sourceSha256": "401d8c924a06e1d1c213df0d6352b9eface9781ee3c3b9de928fe09188dd6c41",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1075530,
    "visiblePixels": 496986,
    "bounds": {
      "x": 31,
      "y": 20,
      "width": 1205,
      "height": 1200
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "goblimon",
    "digibankId": "rookie-goblimon",
    "name": "Goblimon",
    "partner": "Yusuke Shiteru",
    "stage": "rookie",
    "element": "Terra",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/goblimon.png",
    "source": "https://digimon.net/cimages/digimon/goburimon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/goburimon.jpg",
    "sourceSha256": "a415b4868b85c581ebba4fb1652e9a5fe45667481145d48b0f485155390b639a",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 960594,
    "visiblePixels": 611922,
    "bounds": {
      "x": 0,
      "y": 21,
      "width": 1242,
      "height": 1233
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "syakomon",
    "digibankId": "rookie-syakomon",
    "name": "Syakomon",
    "partner": "Ayasaki Harumi",
    "stage": "rookie",
    "element": "Água",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/syakomon.png",
    "source": "https://digimon.net/cimages/digimon/shakomon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/shakomon.jpg",
    "sourceSha256": "e74afa7097e724be188e7b02ac5efa89a719c586981ea7a91b1e09772dea75ce",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1032443,
    "visiblePixels": 540073,
    "bounds": {
      "x": 63,
      "y": 24,
      "width": 1127,
      "height": 1230
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "dracmon",
    "digibankId": "rookie-dracmon",
    "name": "Dracmon",
    "partner": "Sasagakure Jin",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/dracmon.png",
    "source": "https://digimon.net/cimages/digimon/dracumon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/dracumon.jpg",
    "sourceSha256": "7311ff0fc08a9b01f16fff8f3ffce84d3ff2d95a7d305a885e84234303d1f719",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 950192,
    "visiblePixels": 622324,
    "bounds": {
      "x": 0,
      "y": 19,
      "width": 1238,
      "height": 1235
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "veemon",
    "digibankId": "rookie-veemon",
    "name": "Veemon",
    "partner": "Flat Escardos",
    "stage": "rookie",
    "element": "Neutro",
    "digitalAttribute": "Free",
    "image": "assets/partners/veemon.png",
    "source": "https://digimon.net/cimages/digimon/v-mon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/v-mon.jpg",
    "sourceSha256": "b5b81f11893cbea69173d05cbcb80cf4bb9567e52c5310bafb76690066da1cd5",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1095197,
    "visiblePixels": 477319,
    "bounds": {
      "x": 25,
      "y": 45,
      "width": 1197,
      "height": 1165
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "keramon",
    "digibankId": "rookie-keramon",
    "name": "Keramon",
    "partner": "Mogami Erina",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Unknown",
    "image": "assets/partners/keramon.png",
    "source": "https://digimon.net/cimages/digimon/keramon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/keramon.jpg",
    "sourceSha256": "aa5884b9f365724a39b4591e7e1325429f90cc4b3d75ffd402a6efc3762a4db3",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1270856,
    "visiblePixels": 301660,
    "bounds": {
      "x": 31,
      "y": 30,
      "width": 1203,
      "height": 1224
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "tsukaimon",
    "digibankId": "rookie-tsukaimon",
    "name": "Tsukaimon",
    "partner": "Yukihime Rei",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/tsukaimon.png",
    "source": "https://digimon.net/cimages/digimon/tukaimon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/tukaimon.jpg",
    "sourceSha256": "d8ce2b9ca13d366f0d49d2314403bf429ab9ed966534e8d2ecbe3767fcf9f34a",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1108722,
    "visiblePixels": 463794,
    "bounds": {
      "x": 0,
      "y": 0,
      "width": 1208,
      "height": 1190
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "loogamon",
    "digibankId": "rookie-loogamon",
    "name": "Loogamon",
    "partner": "Mutsumi Berkenbosch",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Vírus",
    "image": "assets/partners/loogamon.png",
    "source": "https://digimon.net/cimages/digimon/loogamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/loogamon.jpg",
    "sourceSha256": "2594d8b7b5408ab4b2863d74a4a6bd846d157b77f78b85f7b3ab91f57aca7c17",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 969590,
    "visiblePixels": 602926,
    "bounds": {
      "x": 0,
      "y": 15,
      "width": 1253,
      "height": 1221
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "morphomon",
    "digibankId": "rookie-morphomon",
    "name": "Morphomon",
    "partner": "Yamato Kencho",
    "stage": "rookie",
    "element": "Vento",
    "digitalAttribute": "Vacina",
    "image": "assets/partners/morphomon.png",
    "source": "https://digimon.net/cimages/digimon/morphomon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/morphomon.jpg",
    "sourceSha256": "0e4911296abf7e25010daf552ff1011341f6fa68d641396387b8700c68287727",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1005895,
    "visiblePixels": 566621,
    "bounds": {
      "x": 0,
      "y": 13,
      "width": 1216,
      "height": 1241
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "flamon",
    "digibankId": "rookie-flamon",
    "name": "Flamemon",
    "partner": "Uzuki Akamine",
    "stage": "rookie",
    "element": "Fogo",
    "digitalAttribute": "Variable",
    "image": "assets/partners/flamon.png",
    "source": "https://digimon.net/cimages/digimon/flamon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/flamon.jpg",
    "sourceSha256": "ab38413f607146708c20cefd32125fbe2e50f845fabf67a8223ce2619ab65e93",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 1141497,
    "visiblePixels": 431019,
    "bounds": {
      "x": 0,
      "y": 17,
      "width": 1246,
      "height": 1219
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "hyemon",
    "digibankId": "rookie-hyemon",
    "name": "Hyemon",
    "partner": "Kowagakure Usajirō",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Data",
    "image": "assets/partners/hyemon.png",
    "source": "https://digimon.net/cimages/digimon/hyemon.jpg",
    "sourceImage": "https://digimon.net/cimages/digimon/hyemon.jpg",
    "sourceSha256": "0ac40bf190b7d6b4f3b848f9581a476da8dc10cffea7c6e322439db150af9c64",
    "transparent": true,
    "width": 1254,
    "height": 1254,
    "transparentPixels": 972401,
    "visiblePixels": 600115,
    "bounds": {
      "x": 0,
      "y": 23,
      "width": 1253,
      "height": 1199
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  },
  {
    "id": "black-strabimon",
    "digibankId": "rookie-black-strabimon",
    "name": "Black Strabimon",
    "partner": "Kurogane Kōga",
    "stage": "rookie",
    "element": "Escuridão",
    "digitalAttribute": "Vírus",
    "image": "assets/black-strabimon.png",
    "source": "./assets/digibank/black-strabimon.png",
    "sourceImage": "./assets/digibank/black-strabimon.png",
    "sourceSha256": "ffefbf8be941d4d84305a34a8bc1a706d1d0d1c31ba13d6d43e754d1f30ee8f0",
    "transparent": true,
    "width": 1202,
    "height": 1309,
    "transparentPixels": 990748,
    "visiblePixels": 582670,
    "bounds": {
      "x": 15,
      "y": 0,
      "width": 1186,
      "height": 1291
    },
    "pixelArt": false,
    "processing": "image_gen / background extraction"
  }
];

const key=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases={piyomon:'biyomon',vmon:'veemon',shakomon:'syakomon',plotmon:'salamon',dracumon:'dracmon',flamon:'flamemon',gabumonblack:'blackgabumon'};
export function findSheetArt(name){const n=key(name),canonical=aliases[n]||n;return sheetArt.find(a=>key(a.name)===canonical||key(a.id)===canonical);}
export function sheetSprite(name,fallback=''){return findSheetArt(name)?.image||fallback;}
